changelog:
  categories:
    - title: "⚠️ Breaking Changes"
      labels:
        - "breaking"
        - "semver-major"
    - title: "Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "Security"
      labels:
        - "security"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Performance"
      labels:
        - "performance"
    - title: "CI / Build"
      labels:
        - "ci"
        - "build"
        - "dependencies"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
