/**
 * How a stylesheet is told to read csszyx's safelist: the `@source` directive
 * Tailwind v4 needs, and the checks around adding one.
 *
 * Kept apart from the bundler plugin so the PostCSS entry, which runs inside
 * Next's PostCSS worker, loads only this and not the whole plugin.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { normalizePathSeparators } from './path-normalization.js';

/**
 * The safelist file, relative to the project root. Every producer writes it
 * here by default: the Vite, Rollup and webpack plugins, `csszyx next
 * prebuild` and `csszyx next watch`, and the Next Turbopack loader. It sits
 * in `.csszyx/` with csszyx's other generated state, so one ignore entry
 * covers all of it; Tailwind scans a file named by `@source` even inside an
 * ignored dot-directory.
 */
export const SAFELIST_FILE = '.csszyx/csszyx-classes.txt';

/** Safelist files the PostCSS plugin names when given none. */
export const DEFAULT_SAFELIST_FILES: readonly string[] = [SAFELIST_FILE];

/**
 * Where csszyx wrote the safelist before 0.15.0: an HTML file at the project
 * root, and the name the Next Turbopack setup guide told projects to pass.
 * Recognised so a stale copy can be removed and a stale `@source` explained.
 */
export const LEGACY_SAFELIST_FILES: readonly string[] = [
    'csszyx-classes.html',
    '.csszyx/next-loader-classes.html',
];

/**
 * Text found only in the HTML safelists csszyx wrote before 0.15.0: the
 * bundler plugins' header comment, the empty-file comment of the Next
 * producers, and the marker every non-empty file of either kind put in front
 * of its raw candidates. The Next producers wrote no header once a file held
 * a class, so the candidates marker is the one those files carry.
 *
 * Each marker is an HTML comment, so today's plain-text file, whose header
 * shares words with the old one, never matches — a project may still put it
 * at an old name through `--output-file` or the loader's `safelistOutputFile`.
 */
const LEGACY_HTML_MARKERS = [
    '<!-- Auto-generated by csszyx',
    '<!-- csszyx Next safelist',
    '<!-- csszyx exact scanner candidates -->',
];

/**
 * Remove the pre-0.15.0 safelist files csszyx itself wrote and say where the
 * safelist lives now.
 *
 * Only a file carrying csszyx's own header is touched: an author's file that
 * happens to share the name is not ours to delete.
 *
 * Removing the file is what makes this quiet on every later call, so there is
 * no separate warned-already flag. A file that comes back is something
 * recreating it, and saying so again is the right answer.
 *
 * @param rootDir - project root the legacy files would sit under.
 * @param warn - receives one message per removed file.
 */
export function removeLegacySafelists(rootDir: string, warn: (message: string) => void): void {
    for (const legacy of LEGACY_SAFELIST_FILES) {
        const file = path.join(rootDir, legacy);
        let content: string;
        try {
            content = fs.readFileSync(file, 'utf8');
        } catch {
            continue;
        }
        if (!LEGACY_HTML_MARKERS.some(marker => content.includes(marker))) continue;
        try {
            fs.rmSync(file, { force: true });
        } catch (error) {
            // The safelist this sweep follows is already written; a leftover
            // nobody can delete is not worth the build.
            const { message } = error as NodeJS.ErrnoException;
            warn(`[csszyx] could not remove ${legacy}: ${message}. Delete it by hand.`);
            continue;
        }
        warn(
            `[csszyx] removed ${legacy}: the safelist now lives at ${SAFELIST_FILE}. ` +
                `Update any hand-written @source that named the old file, or drop it and ` +
                `list '@csszyx/unplugin/postcss' before '@tailwindcss/postcss' in postcss.config.`,
        );
    }
}

const LEGACY_SAFELIST_BASENAMES = new Set(
    LEGACY_SAFELIST_FILES.map(file => path.posix.basename(file)),
);

/** An `@source` directive that still names a pre-0.15.0 safelist. */
export interface LegacySourceDirective {
    /** The directive as written, without its `;`. */
    directive: string;
    /** The path it names, as written. */
    target: string;
}

/**
 * Whether an `@source` target names an old csszyx safelist that is not there.
 *
 * A file the author keeps at the old name is theirs and stays scannable;
 * only a dangling reference is the mistake worth stopping a build for,
 * because Tailwind scans nothing for a missing path and says nothing.
 *
 * @param target - the `@source` path as written, relative to the stylesheet.
 * @param cssFile - absolute path of the stylesheet.
 * @returns true when the target is an old safelist name with no file behind it.
 */
export function isDanglingLegacySource(target: string, cssFile: string): boolean {
    if (!LEGACY_SAFELIST_BASENAMES.has(path.posix.basename(target))) return false;
    return !fs.existsSync(path.resolve(path.dirname(cssFile), target));
}

/**
 * Find the first `@source` in a stylesheet that still names an old safelist
 * with no file behind it. Comments are stripped first; `@source not` is a
 * different directive and is left alone.
 *
 * @param code - stylesheet source.
 * @param cssFile - absolute path of the stylesheet.
 * @returns the offending directive, or null.
 */
export function findLegacySourceDirective(
    code: string,
    cssFile: string,
): LegacySourceDirective | null {
    const withoutComments = stripCssBlockComments(code);
    for (const match of withoutComments.matchAll(/@source\s+(["'])([^"']+)\1/g)) {
        const target = match[2];
        if (isDanglingLegacySource(target, cssFile)) {
            return { directive: match[0], target };
        }
    }
    return null;
}

/** Directories no stylesheet of the project itself lives in. */
const SKIPPED_DIRS = new Set([
    'node_modules',
    '.git',
    '.csszyx',
    'dist',
    'build',
    'out',
    'coverage',
    '.turbo',
    '.vercel',
]);

const STYLESHEET_EXTENSIONS = new Set(['.css', '.pcss', '.postcss']);

/** A stylesheet found still naming an old safelist, with the directive. */
export interface LegacySourceStylesheet extends LegacySourceDirective {
    /** Absolute path of the stylesheet. */
    file: string;
}

/**
 * Find a stylesheet under the project that still names an old safelist with
 * no file behind it.
 *
 * The bundler plugins meet every stylesheet in their CSS transform and stop
 * there; the Next lanes have no such hook, so the producers that always run
 * there (prebuild, watch, the loader) look for themselves. Dependency, build
 * and generated trees are skipped, as is any `.next*` output directory.
 *
 * @param rootDir - project root.
 * @returns the first offending stylesheet, or null.
 */
export function findLegacySourceStylesheet(rootDir: string): LegacySourceStylesheet | null {
    const pending = [rootDir];
    while (pending.length > 0) {
        const dir = pending.pop() as string;
        for (const entry of readDirectory(dir)) {
            if (entry.isDirectory()) {
                if (!isSkippedDirectory(entry.name)) pending.push(path.join(dir, entry.name));
                continue;
            }
            const found = readLegacySourceDirective(dir, entry);
            if (found !== null) return found;
        }
    }
    return null;
}

/**
 * @param dir - directory to list.
 * @returns its entries, or none when it cannot be read.
 */
function readDirectory(dir: string): fs.Dirent[] {
    try {
        return fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return [];
    }
}

/**
 * @param name - directory name.
 * @returns whether the walk stays out of it: dependency, build and generated
 *   trees hold no stylesheet the project wrote, and `.next*` is Next's output.
 */
function isSkippedDirectory(name: string): boolean {
    return SKIPPED_DIRS.has(name) || name.startsWith('.next');
}

/**
 * @param dir - directory holding the entry.
 * @param entry - a non-directory entry from that directory.
 * @returns the offending directive when this entry is a stylesheet naming an
 *   old safelist that is gone, otherwise null.
 */
function readLegacySourceDirective(dir: string, entry: fs.Dirent): LegacySourceStylesheet | null {
    if (!entry.isFile() || !STYLESHEET_EXTENSIONS.has(path.extname(entry.name))) return null;
    const file = path.join(dir, entry.name);
    const code = fs.readFileSync(file, 'utf8');
    if (!code.includes('@source')) return null;
    const found = findLegacySourceDirective(code, file);
    return found === null ? null : { file, ...found };
}

const ROOTS_WITHOUT_LEGACY_SOURCE = new Set<string>();

/**
 * Fail the way the bundler plugins do when a stylesheet still names an old
 * safelist. A root found clean is not walked again in this process: the
 * Turbopack loader runs once per module.
 *
 * @param rootDir - project root.
 * @throws when a stylesheet under the root names an old safelist that is gone.
 */
export function assertNoLegacySourceStylesheet(rootDir: string): void {
    if (ROOTS_WITHOUT_LEGACY_SOURCE.has(rootDir)) return;
    const found = findLegacySourceStylesheet(rootDir);
    if (found !== null) throw new Error(legacySourceMessage(found.file, found.target));
    ROOTS_WITHOUT_LEGACY_SOURCE.add(rootDir);
}

/** The PostCSS plugin a Next.js project reads the safelist through. */
export const CSSZYX_POSTCSS_PLUGIN = '@csszyx/unplugin/postcss';

/**
 * Every file Next reads a PostCSS config from, in Next's own search order
 * (`next/dist/lib/find-config`); a `postcss` key in package.json wins first.
 */
export const POSTCSS_CONFIG_FILES: readonly string[] = [
    '.postcssrc.json',
    'postcss.config.json',
    '.postcssrc.js',
    'postcss.config.js',
    'postcss.config.mjs',
    'postcss.config.cjs',
];

/**
 * The PostCSS config Next will read, when it does not list the csszyx plugin.
 *
 * @param rootDir - project root.
 * @returns the config file that lacks the plugin, or null when it lists it or
 *   there is no config for Next to read.
 */
export function findPostcssConfigWithoutCsszyx(rootDir: string): string | null {
    const packageJson = path.join(rootDir, 'package.json');
    let postcssKey: unknown;
    try {
        postcssKey = (JSON.parse(fs.readFileSync(packageJson, 'utf8')) as Record<string, unknown>)
            .postcss;
    } catch {
        postcssKey = undefined;
    }
    if (postcssKey !== undefined) {
        return JSON.stringify(postcssKey).includes(CSSZYX_POSTCSS_PLUGIN) ? null : packageJson;
    }
    for (const name of POSTCSS_CONFIG_FILES) {
        const file = path.join(rootDir, name);
        let text: string;
        try {
            text = fs.readFileSync(file, 'utf8');
        } catch {
            continue;
        }
        return text.includes(CSSZYX_POSTCSS_PLUGIN) ? null : file;
    }
    return null;
}

/**
 * @param configFile - the PostCSS config Next reads.
 * @returns the warning a Next producer prints when that config does not list
 *   the csszyx plugin.
 */
export function missingPostcssPluginMessage(configFile: string): string {
    return (
        `[csszyx] ${configFile} does not list '@csszyx/unplugin/postcss'. Next.js reads the ` +
        `safelist only through that plugin: list it before '@tailwindcss/postcss', or no sz ` +
        `class gets CSS.`
    );
}

/**
 * The message a build fails with when a stylesheet still points at an old
 * safelist. Names the new file and both ways of getting the directive
 * without writing it by hand.
 *
 * @param cssFile - absolute path of the stylesheet.
 * @param target - the old path as written.
 * @returns the complete message.
 */
export function legacySourceMessage(cssFile: string, target: string): string {
    return (
        `[csszyx] ${cssFile}: @source "${target}" names the old safelist, which csszyx no longer writes. ` +
        `The safelist is now ${SAFELIST_FILE}, and csszyx adds the directive itself: remove this line. ` +
        `Vite, Rollup and webpack inject it; on Next.js list '@csszyx/unplugin/postcss' before ` +
        `'@tailwindcss/postcss' in postcss.config.`
    );
}

/**
 * The `tailwindcss` package specifier as it appears in an `@import`: exact or
 * a subpath, ending at the closing quote so a package whose name merely starts
 * with `tailwindcss` (such as `tailwindcss-animate`) does not match. Import
 * options after the quote (`layer(…)`, `source(…)`) are outside the match.
 */
const TAILWIND_SPECIFIER = String.raw`["']tailwindcss(?:\/[^"']*)?["']`;
const TAILWIND_IMPORT = new RegExp(String.raw`@import\s+${TAILWIND_SPECIFIER}`);
const TAILWIND_IMPORT_PARAMS = new RegExp(`^${TAILWIND_SPECIFIER}`);

/**
 * Computes the `@source` target path for a CSS module: the location of the
 * generated safelist file relative to the CSS file, in posix form and always
 * `./`- or `../`-prefixed so Tailwind treats it as a relative path.
 *
 * This is the real-world failure surface — a wrong relative path makes Tailwind
 * silently scan nothing (no error, no CSS), the same symptom as a missing
 * directive — so it is extracted and unit-tested rather than left inline.
 *
 * @param rootDir - project root where the safelist file is written.
 * @param safelistFilename - the safelist path under the root (e.g. `.csszyx/csszyx-classes.txt`).
 * @param cssId - absolute path of the CSS module receiving the directive.
 * @returns the posix relative path from the CSS file to the safelist file.
 */
export function computeSafelistRelPath(
    rootDir: string,
    safelistFilename: string,
    cssId: string,
): string {
    const safelistPath = normalizePathSeparators(path.join(rootDir, safelistFilename));
    const cssDir = normalizePathSeparators(path.dirname(cssId));
    let relPath = path.posix.relative(cssDir, safelistPath);
    // A dot-directory such as `.csszyx/` also starts with `.`; only the two
    // relative prefixes count.
    if (!relPath.startsWith('./') && !relPath.startsWith('../')) {
        relPath = `./${relPath}`;
    }
    return relPath;
}

/**
 * Appends an `@source "<relPath>";` directive to a CSS module so Tailwind v4
 * scans the csszyx-generated safelist file.
 *
 * `@source` is position-independent in Tailwind v4 — it can appear anywhere in
 * the compiled CSS — so the directive is **appended as its own statement**
 * rather than spliced next to the `@import "tailwindcss…"` line. Matching the
 * import syntax is the source of a real defect: the split / manual Tailwind v4
 * setup (`@import "tailwindcss/utilities.css" layer(…)` or `… source(…)`, or an
 * import without a trailing `;`) does not match an import-anchored regex, so the
 * injection silently no-ops and every csszyx-only class (e.g. the static
 * `bg-primary/50` produced by `sz={{ bg: { color, op } }}`) gets no CSS while a
 * raw `className` still works. Appending is correct for every import form.
 *
 * @param code - CSS module source already known to import tailwindcss.
 * @param relPath - safelist path relative to this CSS file (posix, `./`-prefixed).
 * @returns the code with the directive appended, or `null` if it is already
 *   present (idempotent — re-running the transform must not stack directives).
 */
export function appendTailwindSourceDirective(code: string, relPath: string): string | null {
    const directive = `@source "${relPath}";`;
    if (code.includes(directive)) {
        return null;
    }
    const separator = code.length === 0 || code.endsWith('\n') ? '' : '\n';
    return `${code}${separator}${directive}\n`;
}

/**
 * Strip CSS block comments in a single linear pass. The regex form
 * (`/\/\*[\s\S]*?\*\//`) is polynomial-ReDoS on adversarial input such as an
 * unterminated `/*` followed by many `a/*` repetitions (CodeQL
 * js/polynomial-redos), so scan by hand: O(n), no backtracking, copying only
 * the whole non-comment spans.
 *
 * @param code - CSS source that may contain block comments.
 * @returns the source with every block comment removed.
 */
export function stripCssBlockComments(code: string): string {
    const SLASH = 47;
    const STAR = 42;
    let out = '';
    let last = 0;
    let i = 0;
    const n = code.length;
    while (i < n) {
        if (code.codePointAt(i) === SLASH && code.codePointAt(i + 1) === STAR) {
            out += code.slice(last, i);
            i += 2;
            while (i < n && !(code.codePointAt(i) === STAR && code.codePointAt(i + 1) === SLASH)) {
                i++;
            }
            i += 2; // skip past the closing */ (or past EOF if unterminated)
            last = i;
        } else {
            i++;
        }
    }
    return out + code.slice(last);
}

/**
 * Whether a CSS module actually imports the `tailwindcss` package, so the
 * `@source` directive should be appended.
 *
 * Tighter than a substring check on purpose: block comments are stripped first
 * (a commented-out `@import` must not trigger injection), and the package name
 * must end at a quote or a `/` subpath so a different package whose name merely
 * starts with `tailwindcss` (e.g. `tailwindcss-animate`) does not match. Import
 * options after the closing quote (`layer(…)`, `source(…)`) are irrelevant — the
 * match ends at the quote — so every real Tailwind v4 import form is covered.
 *
 * @param code - CSS module source.
 * @returns true if the module imports tailwindcss (exact or a subpath).
 */
export function cssImportsTailwind(code: string): boolean {
    return TAILWIND_IMPORT.test(stripCssBlockComments(code));
}

/**
 * Whether the params of one parsed `@import` at-rule name a file of this
 * project rather than a package.
 *
 * A stylesheet can reach Tailwind through one of these — a shared entry that
 * imports `tailwindcss` itself — and PostCSS runs before any of them are
 * inlined, so the importer is all a plugin sees. Answering yes here is what
 * keeps such an entry from being passed over in silence; an `@source` added
 * to a stylesheet that never becomes a Tailwind entry is never compiled and
 * so costs nothing.
 *
 * @param params - the at-rule's params, e.g. `"./theme.css" layer(base)`.
 * @returns true if the import target is a relative or absolute path.
 */
export function importParamsAreLocal(params: string): boolean {
    let target = params.trim();
    if (target.startsWith('url(')) target = target.slice(4).trim();
    if (target.startsWith('"') || target.startsWith("'")) target = target.slice(1);
    return target.startsWith('./') || target.startsWith('../') || target.startsWith('/');
}

/**
 * Whether the params of one parsed `@import` at-rule name the `tailwindcss`
 * package. The same match as {@link cssImportsTailwind}, for callers that hold
 * an AST instead of source text.
 *
 * @param params - the at-rule's params, e.g. `"tailwindcss" source(none)`.
 * @returns true if the import is of tailwindcss (exact or a subpath).
 */
export function importParamsNameTailwind(params: string): boolean {
    return TAILWIND_IMPORT_PARAMS.test(params.trim());
}
