/**
 * The one renderer for every Tailwind safelist file csszyx writes.
 *
 * The file is plain text: a header, then one class candidate per line.
 * Tailwind v4's scanner reads any file as bytes and takes whitespace-delimited
 * tokens as candidates; the element structure of an HTML file never reaches
 * it. Parent-child CSS such as `space-y-*` or `[&>span]:*` comes from the
 * class NAME, so a bare line produces exactly the CSS a nested `<div>` did.
 * Writing markup was worse than useless: an HTML attribute has to escape
 * `&`, `>` and `"`, and the scanner does not decode entities, so arbitrary
 * variants reached Tailwind as `[&gt;span]` ghosts.
 *
 * Newlines are the only framing the file needs. Every value has already been
 * tokenized by the compiler, so no character in a candidate is treated as
 * special here.
 */

/**
 * Header written at the top of every safelist file. The first line is the
 * marker that identifies a file as csszyx-owned; tooling that decides whether
 * a stale safelist may be removed looks for it.
 */
export const SAFELIST_HEADER: string =
    '<!-- Auto-generated by csszyx — DO NOT EDIT -->\n' +
    '<!-- Tailwind CSS scans this file for class name detection -->\n';

/**
 * Render a safelist file from ordered class candidates.
 *
 * @param classNames - ordered class candidates, already de-duplicated by the caller.
 * @returns the complete file content: header plus one candidate per line.
 */
export function renderSafelistFile(classNames: readonly string[]): string {
    if (classNames.length === 0) {
        return SAFELIST_HEADER;
    }
    return `${SAFELIST_HEADER}${classNames.join('\n')}\n`;
}
