/**
 * Theme Type Writer — generates TypeScript module augmentation for custom tokens.
 *
 * Writes .csszyx/theme.d.ts which augments @csszyx/compiler's CustomTheme
 * interface so IntelliSense surfaces user-defined design tokens in sz prop
 * autocompletion.
 *
 * Output example:
 *   // Auto-generated by csszyx theme-scanner — DO NOT EDIT
 *   declare module '@csszyx/compiler' {
 *     interface CustomTheme {
 *       colors: 'brand' | 'brand-dark';
 *     }
 *   }
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import type { ParsedTheme } from './theme-scanner.js';

/**
 * Escape a token for safe interpolation into a single-quoted TS string literal so
 * a theme token can't break out of the literal or inject a newline into the
 * generated `.d.ts`. Valid tokens contain none of these, so output is
 * byte-identical for normal input — this only neutralizes hostile tokens rather
 * than relying on the upstream scanner's character allowlist.
 *
 * @param value - the raw theme token / key.
 * @returns the escaped literal body.
 */
function escapeTsString(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\r/g, '\\r')
        .replace(/\n/g, '\\n');
}

/** Options for generating the theme .d.ts file. */
export interface ThemeTypeWriterOptions {
    /** Absolute path to write the generated .d.ts file */
    outputPath: string;
    /** Parsed theme tokens to emit */
    theme: ParsedTheme;
    /** Source CSS file(s) — for the attribution comment */
    sourceFiles: string[];
}

/**
 * Generate the content of the theme.d.ts module augmentation file.
 *
 * @param opts - Writer options
 * @returns Generated TypeScript file content
 */
export function generateThemeDts(opts: ThemeTypeWriterOptions): string {
    const { theme, sourceFiles } = opts;
    const timestamp = new Date().toISOString();
    // Strip newlines so a path can never break out of the `// Source:` line
    // comment onto a new line of generated TypeScript.
    const sources = sourceFiles.join(', ').replace(/[\r\n]/g, ' ');

    const toUnion = (tokens: string[]): string =>
        tokens.map(t => `'${escapeTsString(t)}'`).join(' | ');
    // Quote an interface key only when it is not a bare identifier (e.g. '3xl', '2xl').
    const quoteKey = (key: string): string =>
        /^[a-z_$][\w$]*$/i.test(key) ? key : `'${escapeTsString(key)}'`;

    const entries: string[] = [];
    if (theme.colors.length > 0) {
        entries.push(`        colors: ${toUnion(theme.colors)};`);
    }
    if (theme.spacings.length > 0) {
        entries.push(`        spacings: ${toUnion(theme.spacings)};`);
    }
    if (theme.fonts.length > 0) {
        entries.push(`        fonts: ${toUnion(theme.fonts)};`);
    }
    if (theme.textSizes.length > 0) {
        entries.push(`        textSizes: ${toUnion(theme.textSizes)};`);
    }
    if (theme.fontWeights.length > 0) {
        entries.push(`        fontWeights: ${toUnion(theme.fontWeights)};`);
    }
    if (theme.radii.length > 0) {
        entries.push(`        radii: ${toUnion(theme.radii)};`);
    }
    if (theme.shadows.length > 0) {
        entries.push(`        shadows: ${toUnion(theme.shadows)};`);
    }

    // Module body: always the CustomTheme token interface; plus a VariantModifiers
    // augmentation when custom breakpoints (--breakpoint-*) were declared, so
    // `sz={{ tablet: { … } }}` type-checks with no manual augmentation.
    const moduleBody: string[] = [
        '    /**',
        '     * Custom design tokens extracted from @theme blocks.',
        '     * These tokens are surfaced in sz prop IntelliSense.',
        '     */',
        '    interface CustomTheme {',
        ...entries,
        '    }',
    ];

    if (theme.breakpoints.length > 0) {
        const variantEntries = theme.breakpoints.map(
            bp => `        ${quoteKey(bp)}?: SzPropsBase;`,
        );
        moduleBody.push(
            '    /**',
            '     * Custom responsive breakpoints from @theme (--breakpoint-*),',
            '     * surfaced as typed sz variant keys.',
            '     */',
            '    interface VariantModifiers {',
            ...variantEntries,
            '    }',
        );
    }

    return [
        '// Auto-generated by csszyx theme-scanner — DO NOT EDIT',
        `// Source: ${sources}`,
        `// Updated: ${timestamp}`,
        '',
        "declare module '@csszyx/compiler' {",
        ...moduleBody,
        '}',
        '',
        'export {};',
        '',
    ].join('\n');
}

/**
 * Write the theme.d.ts file to disk, creating parent directories as needed.
 *
 * @param opts - Writer options
 */
export function writeThemeDts(opts: ThemeTypeWriterOptions): void {
    const content = generateThemeDts(opts);
    mkdirSync(dirname(opts.outputPath), { recursive: true });
    writeFileSync(opts.outputPath, content, 'utf-8');
}
