import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import { transformSourceCode } from '@csszyx/compiler';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Tests for the incremental HMR class discovery logic in unplugin.ts.
 *
 * These tests verify the behaviour of the handleHotUpdate extension:
 * - New sz classes discovered in a changed file update csszyx-classes.html
 * - Files with no new classes do NOT trigger a file write
 * - Files without sz props are skipped early (perf guard)
 *
 * The actual Vite plugin integration is tested by E2E (packages/e2e).
 * Here we test the pure logic in isolation using the same primitives
 * (transformSourceCode + fs) without spinning up a real Vite server.
 */
describe('HMR incremental class discovery', () => {
    let tmpDir: string,
        safelistPath: string;

    beforeEach(() => {
        tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'csszyx-hmr-'));
        safelistPath = path.join(tmpDir, 'csszyx-classes.html');
    });

    afterEach(() => {
        fs.rmSync(tmpDir, { recursive: true, force: true });
        vi.restoreAllMocks();
    });

    // ---------------------------------------------------------------------------
    // Helpers — mirrors the plugin's writeSafelistFile + handleHotUpdate logic
    // ---------------------------------------------------------------------------

    /**
     * @param classes - the full set of discovered classes to write
     * @param dir - directory to write csszyx-classes.html into
     * @returns true if the file was written, false if it was already up to date
     */
    function writeSafelistFile(classes: Set<string>, dir: string): boolean {
        if (classes.size === 0) { return false; }
        const p = path.join(dir, 'csszyx-classes.html');
        const classList = Array.from(classes).join(' ');
        const content =
            '<!-- Auto-generated by csszyx — DO NOT EDIT -->\n' +
            '<!-- Tailwind CSS scans this file for class name detection -->\n' +
            `<div class="${classList}">` +
            `<div class="${classList}">x</div>` +
            `<div class="${classList}">x</div>` +
            '</div>\n';
        const existing = fs.existsSync(p) ? fs.readFileSync(p, 'utf-8') : '';
        if (existing === content) { return false; }
        fs.writeFileSync(p, content);
        return true;
    }

    /**
     * Simulates what handleHotUpdate does when a source file changes:
     * transforms it, collects new classes, conditionally updates the manifest.
     * @param fileContent - the new content of the changed source file
     * @param existingClasses - the current class set (mutated in place)
     * @param dir - directory containing csszyx-classes.html
     * @returns an object with wrote (whether the manifest was updated) and newClasses (list of added classes)
     */
    function simulateHotUpdate(
        fileContent: string,
        existingClasses: Set<string>,
        dir: string,
    ): { wrote: boolean; newClasses: string[] } {
        if (!fileContent.includes('sz=') && !/\bsz\s*:\s*["'{]/.test(fileContent)) {
            return { wrote: false, newClasses: [] };
        }

        let result: ReturnType<typeof transformSourceCode>;
        try { result = transformSourceCode(fileContent); } catch { return { wrote: false, newClasses: [] }; }
        if (!result.transformed) { return { wrote: false, newClasses: [] }; }

        const sizeBefore = existingClasses.size;
        const added: string[] = [];
        for (const cls of result.classes) {
            if (!existingClasses.has(cls)) { added.push(cls); }
            existingClasses.add(cls);
        }

        const wrote = existingClasses.size > sizeBefore
            ? writeSafelistFile(existingClasses, dir)
            : false;

        return { wrote, newClasses: added };
    }

    // ---------------------------------------------------------------------------
    // Tests
    // ---------------------------------------------------------------------------

    it('writes csszyx-classes.html when a new sz class is discovered', () => {
        const classes = new Set<string>(['p-4', 'bg-blue-500']);
        // Initial manifest
        writeSafelistFile(classes, tmpDir);

        // User adds { mt: 8 } — new class mt-8
        const changed = 'const el = <div sz={{ p: 4, mt: 8 }} />;';
        const { wrote, newClasses } = simulateHotUpdate(changed, classes, tmpDir);

        expect(wrote).toBe(true);
        expect(newClasses).toContain('mt-8');
        const manifest = fs.readFileSync(safelistPath, 'utf-8');
        expect(manifest).toContain('mt-8');
        expect(manifest).toContain('p-4');
    });

    it('does NOT rewrite the manifest when no new classes are found', () => {
        const classes = new Set<string>(['p-4', 'bg-blue-500']);
        writeSafelistFile(classes, tmpDir);
        const statBefore = fs.statSync(safelistPath).mtimeMs;

        // File changed but no new classes (same props, different layout)
        const changed = 'const el = <div sz={{ p: 4, bg: "blue-500" }} />;';
        const { wrote } = simulateHotUpdate(changed, classes, tmpDir);

        expect(wrote).toBe(false);
        // File was not touched (mtime unchanged)
        expect(fs.statSync(safelistPath).mtimeMs).toBe(statBefore);
    });

    it('skips files with no sz prop early', () => {
        const classes = new Set<string>(['p-4']);
        writeSafelistFile(classes, tmpDir);
        const statBefore = fs.statSync(safelistPath).mtimeMs;

        const noSz = 'const el = <div className="text-xl" />;';
        const { wrote } = simulateHotUpdate(noSz, classes, tmpDir);

        expect(wrote).toBe(false);
        expect(fs.statSync(safelistPath).mtimeMs).toBe(statBefore);
    });

    it('handles hover and responsive variant classes', () => {
        const classes = new Set<string>();
        const changed = 'const el = <div sz={{ hover: { bg: "green-500" }, md: { p: 8 } }} />;';
        const { wrote, newClasses } = simulateHotUpdate(changed, classes, tmpDir);

        expect(wrote).toBe(true);
        expect(newClasses).toContain('hover:bg-green-500');
        expect(newClasses).toContain('md:p-8');
    });

    it('accumulates classes across multiple HMR updates', () => {
        const classes = new Set<string>();

        simulateHotUpdate('const a = <div sz={{ p: 4 }} />;', classes, tmpDir);
        simulateHotUpdate('const b = <div sz={{ m: 2 }} />;', classes, tmpDir);
        simulateHotUpdate('const c = <div sz={{ text: "xl" }} />;', classes, tmpDir);

        expect(classes.has('p-4')).toBe(true);
        expect(classes.has('m-2')).toBe(true);
        expect(classes.has('text-xl')).toBe(true);

        const manifest = fs.readFileSync(safelistPath, 'utf-8');
        expect(manifest).toContain('p-4');
        expect(manifest).toContain('m-2');
        expect(manifest).toContain('text-xl');
    });

    it('manifest is HTML with parent and child divs (so Tailwind generates child-selector CSS)', () => {
        const classes = new Set<string>(['space-y-4', 'divide-y', 'p-4']);
        writeSafelistFile(classes, tmpDir);
        const manifest = fs.readFileSync(safelistPath, 'utf-8');
        // Parent div must have the class
        expect(manifest).toMatch(/<div class="[^"]*space-y-4[^"]*">/);
        // Must have at least one child div inside
        expect(manifest).toMatch(/<div class="[^"]*space-y-4[^"]*">x<\/div>/);
    });

    it('does not write when file fails to parse', () => {
        const classes = new Set<string>(['p-4']);
        writeSafelistFile(classes, tmpDir);
        const statBefore = fs.statSync(safelistPath).mtimeMs;

        // Intentionally broken JSX — transformSourceCode should not throw but may return untransformed
        const broken = 'const el = <div sz={{ p: !!!invalid }}} />;';
        // We expect this to be a no-op (either skipped or returns !transformed)
        const { wrote } = simulateHotUpdate(broken, classes, tmpDir);

        // Whether it errors or returns !transformed, the manifest should be unchanged
        if (!wrote) {
            expect(fs.statSync(safelistPath).mtimeMs).toBe(statBefore);
        }
    });
});
