import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { renderSafelistFile, SAFELIST_HEADER } from '../src/safelist-format.js';
import {
    DEFAULT_SAFELIST_FILES,
    LEGACY_SAFELIST_FILES,
    removeLegacySafelists,
    SAFELIST_FILE,
} from '../src/safelist-source.js';

const tempDirs: string[] = [];

afterEach(() => {
    for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

function tempRoot(): string {
    const dir = mkdtempSync(join(tmpdir(), 'csszyx-legacy-'));
    tempDirs.push(dir);
    return dir;
}

describe('safelist file names', () => {
    it('lives under .csszyx as plain text and is what the PostCSS plugin names', () => {
        expect(SAFELIST_FILE).toBe('.csszyx/csszyx-classes.txt');
        expect(DEFAULT_SAFELIST_FILES).toEqual([SAFELIST_FILE]);
        expect(LEGACY_SAFELIST_FILES).toEqual([
            'csszyx-classes.html',
            '.csszyx/next-loader-classes.html',
        ]);
    });

    it('has a header that is text, not markup', () => {
        expect(SAFELIST_HEADER).toContain('Auto-generated by csszyx');
        expect(SAFELIST_HEADER).not.toContain('<');
    });
});

describe('removeLegacySafelists', () => {
    it('deletes the old files csszyx wrote and says where the safelist went, once', () => {
        const root = tempRoot();
        mkdirSync(join(root, '.csszyx'));
        writeFileSync(join(root, 'csszyx-classes.html'), renderSafelistFile(['p-4']));
        writeFileSync(
            join(root, '.csszyx/next-loader-classes.html'),
            '<!-- csszyx Next safelist: empty -->\n',
        );
        const warnings: string[] = [];
        const warn = (message: string) => warnings.push(message);

        removeLegacySafelists(root, warn);
        removeLegacySafelists(root, warn);

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(false);
        expect(existsSync(join(root, '.csszyx/next-loader-classes.html'))).toBe(false);
        expect(warnings).toHaveLength(2);
        expect(warnings[0]).toContain('csszyx-classes.html');
        expect(warnings[0]).toContain(SAFELIST_FILE);
        expect(warnings[0]).toContain("'@csszyx/unplugin/postcss'");
    });

    it('leaves a file it did not write alone', () => {
        const root = tempRoot();
        const theirs = '<div class="p-4"></div>\n';
        writeFileSync(join(root, 'csszyx-classes.html'), theirs);
        const warnings: string[] = [];

        removeLegacySafelists(root, message => warnings.push(message));

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(true);
        expect(warnings).toEqual([]);
    });

    it('does nothing when there is nothing old', () => {
        const root = tempRoot();
        const warnings: string[] = [];
        removeLegacySafelists(root, message => warnings.push(message));
        expect(warnings).toEqual([]);
    });
});
