import { chmodSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { renderSafelistFile, SAFELIST_HEADER } from '../src/safelist-format.js';
import {
    DEFAULT_SAFELIST_FILES,
    findLegacySourceStylesheet,
    findPostcssConfigWithoutCsszyx,
    LEGACY_SAFELIST_FILES,
    removeLegacySafelists,
    SAFELIST_FILE,
} from '../src/safelist-source.js';

const tempDirs: string[] = [];

afterEach(() => {
    for (const dir of tempDirs.splice(0)) {
        chmodSync(dir, 0o755);
        rmSync(dir, { recursive: true, force: true });
    }
});

/** The bytes the Vite, Rollup and webpack plugins wrote before 0.15.0. */
const OLD_VITE_SAFELIST =
    '<!-- Auto-generated by csszyx \u2014 DO NOT EDIT -->\n' +
    '<!-- Tailwind CSS scans this file for class name detection -->\n' +
    '<div class="p-4"><div class="p-4">x</div><div class="p-4">x</div></div>\n' +
    '<!-- csszyx exact scanner candidates -->\np-4\n';

/**
 * The bytes `csszyx next prebuild`, `next watch` and the Turbopack loader
 * wrote before 0.15.0 once they held a class: no header at all, one `div`
 * per class, then the raw candidates behind their marker.
 */
const OLD_NEXT_SAFELIST =
    '<div class="p-4"></div>\n<div class="[&amp;&gt;span]:p-2"></div>\n' +
    '<!-- csszyx exact scanner candidates -->\np-4\n[&>span]:p-2\n';

function tempRoot(): string {
    const dir = mkdtempSync(join(tmpdir(), 'csszyx-legacy-'));
    tempDirs.push(dir);
    return dir;
}

describe('safelist file names', () => {
    it('lives under .csszyx as plain text and is what the PostCSS plugin names', () => {
        expect(SAFELIST_FILE).toBe('.csszyx/csszyx-classes.txt');
        expect(DEFAULT_SAFELIST_FILES).toEqual([SAFELIST_FILE]);
        expect(LEGACY_SAFELIST_FILES).toEqual([
            'csszyx-classes.html',
            '.csszyx/next-loader-classes.html',
        ]);
    });

    it('has a header that is text, not markup', () => {
        expect(SAFELIST_HEADER).toContain('Auto-generated by csszyx');
        expect(SAFELIST_HEADER).not.toContain('<');
    });
});

describe('findLegacySourceStylesheet', () => {
    /**
     * The Next lanes have no CSS hook: nothing transforms the stylesheet, so
     * a hand-written `@source "../csszyx-classes.html"` from the old setup
     * guide survives the upgrade and, once the file is gone, scans nothing in
     * silence. The producers that always run there (prebuild, watch, the
     * loader) look for it themselves.
     */
    it('finds a stylesheet whose @source names an old safelist that is gone', () => {
        const root = tempRoot();
        mkdirSync(join(root, 'app'));
        writeFileSync(
            join(root, 'app/globals.css'),
            '@import "tailwindcss" source(none);\n@source "../csszyx-classes.html";\n',
        );
        const found = findLegacySourceStylesheet(root);
        expect(found).toEqual({
            file: join(root, 'app/globals.css'),
            directive: '@source "../csszyx-classes.html"',
            target: '../csszyx-classes.html',
        });
    });

    it('skips dependency, build and generated trees', () => {
        const root = tempRoot();
        for (const dir of ['node_modules/pkg', '.next/static', '.csszyx', 'dist']) {
            mkdirSync(join(root, dir), { recursive: true });
            writeFileSync(join(root, dir, 'x.css'), '@source "../csszyx-classes.html";\n');
        }
        expect(findLegacySourceStylesheet(root)).toBeNull();
    });

    it('lets a stylesheet stand while the old file is still there', () => {
        const root = tempRoot();
        writeFileSync(join(root, 'csszyx-classes.html'), '<div class="p-4"></div>\n');
        mkdirSync(join(root, 'app'));
        writeFileSync(join(root, 'app/globals.css'), '@source "../csszyx-classes.html";\n');
        expect(findLegacySourceStylesheet(root)).toBeNull();
    });
});

describe('findPostcssConfigWithoutCsszyx', () => {
    it('reads the postcss key of package.json first, the way Next does', () => {
        const root = tempRoot();
        writeFileSync(
            join(root, 'package.json'),
            '{ "name": "app", "postcss": { "plugins": { "@tailwindcss/postcss": {} } } }\n',
        );
        writeFileSync(
            join(root, 'postcss.config.mjs'),
            "export default { plugins: { '@csszyx/unplugin/postcss': {} } };\n",
        );
        expect(findPostcssConfigWithoutCsszyx(root)).toBe(join(root, 'package.json'));
    });

    it('is satisfied by a package.json key that lists the plugin', () => {
        const root = tempRoot();
        writeFileSync(
            join(root, 'package.json'),
            '{ "postcss": { "plugins": { "@csszyx/unplugin/postcss": {}, "@tailwindcss/postcss": {} } } }\n',
        );
        expect(findPostcssConfigWithoutCsszyx(root)).toBeNull();
    });

    it('answers null when Next has no PostCSS config to read', () => {
        const root = tempRoot();
        writeFileSync(join(root, 'package.json'), '{ "name": "app" }\n');
        expect(findPostcssConfigWithoutCsszyx(root)).toBeNull();
    });
});

describe('removeLegacySafelists', () => {
    it('deletes the old files csszyx wrote and says where the safelist went, once', () => {
        const root = tempRoot();
        mkdirSync(join(root, '.csszyx'));
        writeFileSync(join(root, 'csszyx-classes.html'), OLD_VITE_SAFELIST);
        writeFileSync(
            join(root, '.csszyx/next-loader-classes.html'),
            '<!-- csszyx Next safelist: empty -->\n',
        );
        const warnings: string[] = [];
        const warn = (message: string) => warnings.push(message);

        removeLegacySafelists(root, warn);
        removeLegacySafelists(root, warn);

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(false);
        expect(existsSync(join(root, '.csszyx/next-loader-classes.html'))).toBe(false);
        expect(warnings).toHaveLength(2);
        expect(warnings[0]).toContain('csszyx-classes.html');
        expect(warnings[0]).toContain(SAFELIST_FILE);
        expect(warnings[0]).toContain("'@csszyx/unplugin/postcss'");
    });

    it('deletes the Next safelist that held classes, which carried no header', () => {
        const root = tempRoot();
        mkdirSync(join(root, '.csszyx'));
        writeFileSync(join(root, '.csszyx/next-loader-classes.html'), OLD_NEXT_SAFELIST);
        const warnings: string[] = [];

        removeLegacySafelists(root, message => warnings.push(message));

        expect(existsSync(join(root, '.csszyx/next-loader-classes.html'))).toBe(false);
        expect(warnings).toHaveLength(1);
    });

    /**
     * A project can still name its output the old way, through
     * `--output-file` or the loader's `safelistOutputFile`; the writer then
     * puts today's plain-text file at that name. That file is current
     * output, not a leftover, and deleting it would undo the write that
     * just happened.
     */
    it('keeps the safelist csszyx writes today, whatever name it was given', () => {
        const root = tempRoot();
        mkdirSync(join(root, '.csszyx'));
        writeFileSync(join(root, 'csszyx-classes.html'), renderSafelistFile(['p-4']));
        writeFileSync(join(root, '.csszyx/next-loader-classes.html'), renderSafelistFile([]));
        const warnings: string[] = [];

        removeLegacySafelists(root, message => warnings.push(message));

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(true);
        expect(existsSync(join(root, '.csszyx/next-loader-classes.html'))).toBe(true);
        expect(warnings).toEqual([]);
    });

    it('says which old file it could not remove instead of failing the build', () => {
        const root = tempRoot();
        writeFileSync(join(root, 'csszyx-classes.html'), OLD_VITE_SAFELIST);
        chmodSync(root, 0o555);
        const warnings: string[] = [];

        expect(() => removeLegacySafelists(root, message => warnings.push(message))).not.toThrow();

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(true);
        expect(warnings).toHaveLength(1);
        expect(warnings[0]).toContain('could not remove csszyx-classes.html');
    });

    it('leaves a file it did not write alone', () => {
        const root = tempRoot();
        const theirs = '<div class="p-4"></div>\n';
        writeFileSync(join(root, 'csszyx-classes.html'), theirs);
        const warnings: string[] = [];

        removeLegacySafelists(root, message => warnings.push(message));

        expect(existsSync(join(root, 'csszyx-classes.html'))).toBe(true);
        expect(warnings).toEqual([]);
    });

    it('does nothing when there is nothing old', () => {
        const root = tempRoot();
        const warnings: string[] = [];
        removeLegacySafelists(root, message => warnings.push(message));
        expect(warnings).toEqual([]);
    });
});
