//! TS↔Rust parity for `csszyx migrate`.
//!
//! The corpus is generated by `scripts/gen-migrate-parity-corpus.mjs`, which
//! records what migrate's TypeScript answers for every class the goldens, the
//! sz-key matrix, the pinned corpora and a list of edge cases contain. The
//! Rust port replays the same classes and must answer identically — including
//! answering "not recognised" for the same inputs. A divergence is a port bug,
//! not a preference, so it fails closed.

#![cfg(feature = "migrate")]

use csszyx_core::migrate::{class_name_to_sz_object, parse_class, SzObject};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    count: usize,
    entries: Vec<Entry>,
    /// The migration-resolution map the custom-map cases were converted with.
    #[serde(rename = "customMap")]
    custom_map: SzObject,
    #[serde(rename = "customMapCases")]
    custom_map_cases: Vec<ConversionCase>,
}

#[derive(Deserialize)]
struct Entry {
    /// The class as migrate receives it.
    c: String,
    /// What `parseClass` answered, or `null`.
    p: Option<serde_json::Value>,
    /// What `classNameToSzObject` answered.
    o: Conversion,
}

#[derive(Deserialize)]
struct ConversionCase {
    c: String,
    o: Conversion,
}

#[derive(Deserialize)]
struct Conversion {
    /// The sz object as `JSON.stringify` wrote it, keys in its order.
    #[serde(rename = "szText")]
    sz_text: String,
    /// Classes left in `className`.
    u: Vec<String>,
    /// Classes the map said to keep.
    k: Vec<String>,
}

fn corpus() -> Corpus {
    let json = include_str!("fixtures/migrate-parity-corpus.json");
    let corpus: Corpus = serde_json::from_str(json).expect("the migrate parity corpus is JSON");
    assert_eq!(corpus.count, corpus.entries.len());
    assert!(
        corpus.count > 3000,
        "the corpus holds only {} classes",
        corpus.count
    );
    corpus
}

#[test]
fn parse_class_answers_exactly_what_the_typescript_parser_answers() {
    let corpus = corpus();
    let mut recognised = 0;
    let mut mismatches = Vec::new();

    for entry in &corpus.entries {
        let rust = parse_class(&entry.c)
            .map(|parsed| serde_json::to_value(parsed).expect("a parsed class serialises"));
        if rust.is_some() {
            recognised += 1;
        }
        if rust != entry.p {
            mismatches.push(format!(
                "  {:?}\n      ts   = {}\n      rust = {}",
                entry.c,
                entry
                    .p
                    .as_ref()
                    .map_or_else(|| "null".to_string(), ToString::to_string),
                rust.as_ref()
                    .map_or_else(|| "null".to_string(), ToString::to_string),
            ));
        }
    }

    // Two parsers that both recognise nothing also agree on everything.
    assert!(
        recognised > 2000,
        "only {recognised} classes were recognised"
    );
    assert!(
        mismatches.is_empty(),
        "{} of {} classes parse differently from the TypeScript parser:\n{}",
        mismatches.len(),
        corpus.count,
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// One class string through the Rust conversion, rendered the way the
/// corpus renders the TypeScript's answer.
fn convert(class_name: &str, custom_map: Option<&SzObject>) -> (String, Vec<String>, Vec<String>) {
    let converted = class_name_to_sz_object(class_name, custom_map);
    (
        serde_json::to_string(&converted.sz_object).expect("an sz object serialises"),
        converted.unrecognized,
        converted.keep_in_class_name,
    )
}

fn assert_conversions<'a>(
    cases: impl Iterator<Item = (&'a str, &'a Conversion)>,
    custom_map: Option<&SzObject>,
) {
    let mut total = 0;
    let mut mismatches = Vec::new();
    for (class_name, expected) in cases {
        total += 1;
        let actual = convert(class_name, custom_map);
        let wanted = (
            expected.sz_text.clone(),
            expected.u.clone(),
            expected.k.clone(),
        );
        if actual != wanted {
            mismatches.push(format!(
                "  {class_name:?}\n      ts   = {wanted:?}\n      rust = {actual:?}"
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {total} class strings convert differently from the TypeScript:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn class_name_to_sz_object_answers_exactly_what_the_typescript_answers() {
    let corpus = corpus();
    let converted = corpus
        .entries
        .iter()
        .filter(|entry| entry.o.sz_text != "{}")
        .count();
    assert!(
        converted > 2000,
        "only {converted} class strings converted to anything"
    );
    assert_conversions(
        corpus
            .entries
            .iter()
            .map(|entry| (entry.c.as_str(), &entry.o)),
        None,
    );
}

#[test]
fn custom_map_entries_resolve_exactly_as_the_typescript_resolves_them() {
    let corpus = corpus();
    assert!(corpus.custom_map_cases.len() > 20);
    assert_conversions(
        corpus
            .custom_map_cases
            .iter()
            .map(|case| (case.c.as_str(), &case.o)),
        Some(&corpus.custom_map),
    );
}
