//! TS↔Rust parity for `csszyx migrate`.
//!
//! The corpus is generated by `scripts/gen-migrate-parity-corpus.mjs`, which
//! records what migrate's TypeScript answers for every class the goldens, the
//! sz-key matrix, the pinned corpora and a list of edge cases contain. The
//! Rust port replays the same classes and must answer identically — including
//! answering "not recognised" for the same inputs. A divergence is a port bug,
//! not a preference, so it fails closed.

#![cfg(feature = "migrate")]

use csszyx_core::migrate::parse_class;
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    count: usize,
    entries: Vec<Entry>,
}

#[derive(Deserialize)]
struct Entry {
    /// The class as migrate receives it.
    c: String,
    /// What `parseClass` answered, or `null`.
    p: Option<serde_json::Value>,
}

fn corpus() -> Corpus {
    let json = include_str!("fixtures/migrate-parity-corpus.json");
    let corpus: Corpus = serde_json::from_str(json).expect("the migrate parity corpus is JSON");
    assert_eq!(corpus.count, corpus.entries.len());
    assert!(
        corpus.count > 3000,
        "the corpus holds only {} classes",
        corpus.count
    );
    corpus
}

#[test]
fn parse_class_answers_exactly_what_the_typescript_parser_answers() {
    let corpus = corpus();
    let mut recognised = 0;
    let mut mismatches = Vec::new();

    for entry in &corpus.entries {
        let rust = parse_class(&entry.c)
            .map(|parsed| serde_json::to_value(parsed).expect("a parsed class serialises"));
        if rust.is_some() {
            recognised += 1;
        }
        if rust != entry.p {
            mismatches.push(format!(
                "  {:?}\n      ts   = {}\n      rust = {}",
                entry.c,
                entry
                    .p
                    .as_ref()
                    .map_or_else(|| "null".to_string(), ToString::to_string),
                rust.as_ref()
                    .map_or_else(|| "null".to_string(), ToString::to_string),
            ));
        }
    }

    // Two parsers that both recognise nothing also agree on everything.
    assert!(
        recognised > 2000,
        "only {recognised} classes were recognised"
    );
    assert!(
        mismatches.is_empty(),
        "{} of {} classes parse differently from the TypeScript parser:\n{}",
        mismatches.len(),
        corpus.count,
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
