//! TS↔Rust lowering parity.
//!
//! The corpus is generated by `scripts/gen-rust-parity-corpus.mjs`, which
//! records the canonical Babel/oxc `transform()` className for each sz object.
//! This test replays the same objects through the native `lower_static_sz_object`
//! and fails closed on any class-output divergence, since the rust path is the
//! shipped default parser.
//!
//! `KNOWN_DIVERGENCES` enumerates the gaps the harness has already surfaced but
//! that are not yet ported. They are tracked here so the suite stays green while
//! the list can only shrink: a known case that starts matching, or a new case
//! that starts diverging, both fail the test.

use csszyx_core::transform::lower::lower_static_sz_object;
use csszyx_core::transform::StaticSzObject;

/// sz objects whose rust lowering is known to diverge from the oxc path,
/// pending a port. Each entry must be removed once the gap is closed.
const KNOWN_DIVERGENCES: &[&str] = &[
    // Variant subsystem: `group`/`peer` scope sugar combines with the nested
    // variant via `-` (group-hover), and `supports`/`not` are parametric
    // variants; the rust path chains every nesting level with a plain `:`.
    r#"{"group":{"hover":{"color":"white"}}}"#,
    r#"{"peer":{"focus":{"text":"red-500"}}}"#,
    r#"{"supports":{"display:grid":{"grid":true}}}"#,
    r#"{"not":{"first":{"mt":4}}}"#,
];

#[derive(serde::Deserialize)]
struct ParityRecord {
    sz: String,
    ir: StaticSzObject,
    oxc: String,
}

#[test]
fn ts_rust_lowering_parity() {
    let json = include_str!("fixtures/parity-corpus.json");
    let records: Vec<ParityRecord> =
        serde_json::from_str(json).expect("parity corpus must be valid JSON");
    assert!(!records.is_empty(), "parity corpus is empty");

    let mut unexpected = Vec::new();
    let mut newly_fixed = Vec::new();

    for record in &records {
        let rust = lower_static_sz_object(&record.ir).join(" ");
        let diverges = rust != record.oxc;
        let known = KNOWN_DIVERGENCES.contains(&record.sz.as_str());

        if diverges && !known {
            unexpected.push(format!(
                "  sz {}\n      oxc  = {:?}\n      rust = {:?}",
                record.sz, record.oxc, rust
            ));
        } else if !diverges && known {
            newly_fixed.push(record.sz.clone());
        }
    }

    assert!(
        unexpected.is_empty(),
        "{} new TS↔Rust lowering divergence(s) — the rust default parser does not match oxc:\n{}",
        unexpected.len(),
        unexpected.join("\n")
    );
    assert!(
        newly_fixed.is_empty(),
        "{} entr(ies) now match — remove them from KNOWN_DIVERGENCES:\n  {}",
        newly_fixed.len(),
        newly_fixed.join("\n  ")
    );
}
