// Auto-generated by csszyx — DO NOT EDIT
// Tailwind CSS scans this file for class name detection
export default "min-h-[100vh] bg-slate-900 text-white p-8 font-sans max-w-2xl mx-auto text-4xl text-center text-blue-400 font-bold mb-6 grid grid-cols-1 md:grid-cols-2 gap-6 p-6 bg-slate-800 rounded-xl border-slate-700 hover:border-blue-500 transition-colors text-xl font-semibold mb-3 text-slate-400 hover:border-purple-500 mt-12 px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium";
