// @generated by scripts/gen-diagnostic-codes.mjs
// Do not edit by hand. Edit the list in that script instead.

/** What kind of problem one engine diagnostic reports. */
export type SzDiagnosticCode =
    | 'unknown-key'
    | 'canonical-key'
    | 'removed-key'
    | 'numeric-key'
    | 'closed-enum-value'
    | 'off-scale-value'
    | 'numeric-font-weight'
    | 'per-side-border-style'
    | 'property-object'
    | 'non-variant-object'
    | 'unknown-field'
    | 'runtime-value'
    | 'unresolvable-spread'
    | 'style-override'
    | 'szs-slot-map'
    | 'sz-recover'
    | 'class-precedence'
    | 'duplicate-sz'
    | 'spread-split-class'
    | 'moved-value'
    | 'global-before-group'
    | 'runtime-family-conflict'
    | 'fallback-missing-css'
    | 'fallback-nudge'
    | 'merge-classifier-unavailable'
    | 'parse-error'
    | 'nesting-depth'
    | 'unsupported-dynamic-sz'
    | 'ast-budget'
    | 'mangle-vars-hoist-skipped';

/** Every code the engine produces, in the order `csszyx check` lists them. */
export const SZ_DIAGNOSTIC_CODES: readonly SzDiagnosticCode[] = [
    'unknown-key',
    'canonical-key',
    'removed-key',
    'numeric-key',
    'closed-enum-value',
    'off-scale-value',
    'numeric-font-weight',
    'per-side-border-style',
    'property-object',
    'non-variant-object',
    'unknown-field',
    'runtime-value',
    'unresolvable-spread',
    'style-override',
    'szs-slot-map',
    'sz-recover',
    'class-precedence',
    'duplicate-sz',
    'spread-split-class',
    'moved-value',
    'global-before-group',
    'runtime-family-conflict',
    'fallback-missing-css',
    'fallback-nudge',
    'merge-classifier-unavailable',
    'parse-error',
    'nesting-depth',
    'unsupported-dynamic-sz',
    'ast-budget',
    'mangle-vars-hoist-skipped',
];
