import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

import {
    SZ_FALLBACK_KINDS,
    SZ_FALLBACK_MATRIX,
} from '../packages/compiler/src/sz-fallback-matrix.js';
import {
    escapeRustFormat,
    escapeRustString,
    GENERATED_PATH,
    generateMatrixSource,
    renderReasonArm,
    renderRust,
    variantName,
} from './gen-sz-fallback-matrix.mjs';

describe('sz fallback matrix generation', () => {
    it('keeps the committed Rust copy byte-identical to the matrix', () => {
        // The CI gate runs the same comparison; asserting it here means a stale
        // copy fails in the unit run too, not only in the workflow step.
        assert.equal(readFileSync(GENERATED_PATH, 'utf8'), generateMatrixSource());
    });

    it('names a multi-word kind in PascalCase, with no separator left in it', () => {
        // Spelled out here so the check below can use the generator's own
        // naming without losing the naming rule itself. A hand-rolled copy of
        // this rule is what let a kebab-case kind through: capitalising the
        // first letter alone left the hyphen in the middle, and the count it
        // then looked for was of a variant that is never emitted.
        assert.equal(variantName('szv-factory'), 'SzvFactory');
        assert.equal(variantName('call'), 'Call');
    });

    it('emits one match arm per kind, for both reason and suggestion', () => {
        const source = renderRust();
        for (const kind of SZ_FALLBACK_KINDS) {
            const variant = variantName(kind);
            // Once in the enum, once in each of the two match statements.
            const occurrences = source.split(`SzFallbackKind::${variant}`).length - 1;
            assert.equal(occurrences, 2, `${kind} should appear in both match statements`);
            assert.ok(source.includes(`    ${variant},`), `${kind} should be an enum variant`);
        }
    });

    it('carries every suggestion through verbatim', () => {
        const source = renderRust();
        for (const kind of SZ_FALLBACK_KINDS) {
            assert.ok(
                source.includes(SZ_FALLBACK_MATRIX[kind].suggestion),
                `${kind} suggestion should survive generation unchanged`,
            );
        }
    });

    it('renders a detail-carrying reason as an inline format argument', () => {
        // `call` interpolates; a plain String::from would drop the name.
        assert.match(renderReasonArm('call'), /^format!\(".*\{detail\}.*"\)$/);
    });

    it('renders a detail-free reason without formatting machinery', () => {
        // `member` has nothing to interpolate; format! would only cost work.
        assert.equal(
            renderReasonArm('member'),
            `String::from("${SZ_FALLBACK_MATRIX.member.reason}")`,
        );
    });

    it('escapes quotes and backslashes for a Rust string literal', () => {
        assert.equal(escapeRustString('say "hi"'), 'say \\"hi\\"');
        assert.equal(escapeRustString('back\\slash'), 'back\\\\slash');
        // Backslash first, then quote — escaping in the other order would
        // double-escape the backslash it just inserted.
        assert.equal(escapeRustString('\\"'), '\\\\\\"');
    });

    it('escapes braces so a literal brace cannot become a format argument', () => {
        assert.equal(escapeRustFormat('a {b} c'), 'a {{b}} c');
        assert.equal(escapeRustFormat('{}'), '{{}}');
    });

    it('refuses a reason that repeats the placeholder', () => {
        // The Rust renderer supplies one inline argument; a second placeholder
        // would compile but reference an argument that is not there.
        const original = SZ_FALLBACK_MATRIX.other.reason;
        const mutable = SZ_FALLBACK_MATRIX as unknown as Record<string, { reason: string }>;
        mutable.other.reason = '{detail} and {detail}';
        try {
            assert.throws(() => renderReasonArm('other'), /repeats/);
        } finally {
            mutable.other.reason = original;
        }
    });

    it('marks the output as generated so nobody edits it by hand', () => {
        const source = renderRust();
        assert.ok(source.startsWith('// @generated by scripts/gen-sz-fallback-matrix.mjs'));
        assert.ok(source.includes('Edit packages/compiler/src/sz-fallback-matrix.ts instead.'));
    });
});
