/**
 * @csszyx/compiler - TypeScript type definitions for sz prop.
 *
 * This module provides comprehensive type definitions for the sz prop
 * to enable IntelliSense, autocompletion, and type safety.
 *
 * @module @csszyx/compiler/types
 */

import type * as CSS from 'csstype';

// ============================================================================
// Custom Theme Augmentation
// ============================================================================

/**
 * Augmentable interface for user-defined Tailwind v4 design tokens.
 *
 * Users (or the theme-scanner plugin) extend this via module augmentation so
 * that custom tokens appear in sz prop IntelliSense without requiring
 * changes to the core types.
 *
 * @example
 * // In .csszyx/theme.d.ts (auto-generated by @csszyx/unplugin scanCss option):
 * declare module '@csszyx/compiler' {
 *   interface CustomTheme {
 *     colors: 'brand' | 'brand-dark';
 *     spacings: 'xl' | '2xs';
 *   }
 * }
 *
 * biome-ignore lint/complexity/noBannedTypes: this empty object type is the module-augmentation anchor.
 */
export type CustomTheme = {};

/** Extracts custom color tokens from CustomTheme, or never if not defined. */
type CT_Colors = CustomTheme extends { colors: infer T } ? T : never;
/** Extracts custom spacing tokens from CustomTheme, or never if not defined. */
type CT_Spacings = CustomTheme extends { spacings: infer T } ? T : never;
/** Extracts custom font tokens from CustomTheme, or never if not defined. */
type CT_Fonts = CustomTheme extends { fonts: infer T } ? T : never;
/** Extracts custom border-radius tokens from CustomTheme, or never if not defined. */
type CT_Radii = CustomTheme extends { radii: infer T } ? T : never;
/** Extracts custom shadow tokens from CustomTheme, or never if not defined. */
type CT_Shadows = CustomTheme extends { shadows: infer T } ? T : never;

// ============================================================================
// Helper Types
// ============================================================================

/**
 * Tailwind v4 spacing scale.
 *
 * Common preset values are listed for IDE autocomplete. Any number is valid —
 * Tailwind v4's dynamic spacing system resolves n to `calc(var(--spacing) * n)`
 * (e.g. w-13, w-92, p-1.5, p-2.5 are all valid).
 */
export type SpacingScale =
    | 0
    | 0.5
    | 1
    | 1.5
    | 2
    | 2.5
    | 3
    | 3.5
    | 4
    | 5
    | 6
    | 7
    | 8
    | 9
    | 10
    | 11
    | 12
    | 14
    | 16
    | 20
    | 24
    | 28
    | 32
    | 36
    | 40
    | 44
    | 48
    | 52
    | 56
    | 60
    | 64
    | 72
    | 80
    | 96
    | (number & {}); // Tailwind v4: any positive number is valid

/** Spacing value that can be scale, keyword, arbitrary, or custom token */
export type SpacingValue =
    | SpacingScale
    | 'px'
    | 'auto'
    | CT_Spacings
    | (number & {})
    | (string & {});

/** Negative spacing value */
export type NegativeSpacingValue = SpacingValue | number;

/** Tailwind color names */
export type ColorName =
    | 'inherit'
    | 'current'
    | 'transparent'
    | 'black'
    | 'white'
    | 'slate'
    | 'gray'
    | 'zinc'
    | 'neutral'
    | 'stone'
    | 'red'
    | 'orange'
    | 'amber'
    | 'yellow'
    | 'lime'
    | 'green'
    | 'emerald'
    | 'teal'
    | 'cyan'
    | 'sky'
    | 'blue'
    | 'indigo'
    | 'violet'
    | 'purple'
    | 'fuchsia'
    | 'pink'
    | 'rose'
    | 'mauve'
    | 'olive'
    | 'mist'
    | 'taupe';

/** Tailwind color shades */
export type ColorShade = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950;

/** Color value (string-based) */
export type ColorValue =
    | 'inherit'
    | 'current'
    | 'transparent'
    | 'black'
    | 'white'
    | `${ColorName}-${ColorShade}`
    | CT_Colors
    | (string & {});

/** Color object with opacity */
export interface ColorObjectValue {
    color: ColorValue;
    op?: number | (string & {});
}

/** Union type for all color properties */
export type ColorPropValue = ColorValue | ColorObjectValue;

/** Container size names */
export type ContainerSize =
    | '3xs'
    | '2xs'
    | 'xs'
    | 'sm'
    | 'md'
    | 'lg'
    | 'xl'
    | '2xl'
    | '3xl'
    | '4xl'
    | '5xl'
    | '6xl'
    | '7xl';

/**
 * Fraction values for sizing/layout props.
 *
 * Common fractions are listed for IDE autocomplete. Any `n/m` string is valid —
 * Tailwind v4 accepts arbitrary numerator/denominator (e.g. '3/7', '5/9', '11/16').
 */
export type FractionValue =
    | '1/2'
    | '1/3'
    | '2/3'
    | '1/4'
    | '2/4'
    | '3/4'
    | '1/5'
    | '2/5'
    | '3/5'
    | '4/5'
    | '1/6'
    | '2/6'
    | '3/6'
    | '4/6'
    | '5/6'
    | '1/12'
    | '2/12'
    | '3/12'
    | '4/12'
    | '5/12'
    | '6/12'
    | '7/12'
    | '8/12'
    | '9/12'
    | '10/12'
    | '11/12'
    | (string & {}); // Tailwind v4: any n/m fraction is valid

/** Border radius keywords */
export type BorderRadiusValue =
    | 'none'
    | 'sm'
    | 'md'
    | 'lg'
    | 'xl'
    | '2xl'
    | '3xl'
    | 'full'
    | CT_Radii
    | true
    | (string & {});

/** Shadow keywords */
export type ShadowValue =
    | 'sm'
    | 'md'
    | 'lg'
    | 'xl'
    | '2xl'
    | 'inner'
    | 'none'
    | CT_Shadows
    | true
    | (string & {});

// ============================================================================
// Layout Properties
// ============================================================================

/**
 *
 */
export interface LayoutProps {
    /** @see https://tailwindcss.com/docs/aspect-ratio */
    aspect?: 'auto' | 'square' | 'video' | (string & {});

    /** @see https://tailwindcss.com/docs/columns */
    columns?:
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 'auto'
        | ContainerSize
        | (string & {});

    /** @see https://tailwindcss.com/docs/break-after */
    breakAfter?: 'auto' | 'avoid' | 'all' | 'avoid-page' | 'page' | 'left' | 'right' | 'column';

    /** @see https://tailwindcss.com/docs/break-before */
    breakBefore?: 'auto' | 'avoid' | 'all' | 'avoid-page' | 'page' | 'left' | 'right' | 'column';

    /** @see https://tailwindcss.com/docs/break-inside */
    breakInside?: 'auto' | 'avoid' | 'avoid-page' | 'avoid-column';

    /** @see https://tailwindcss.com/docs/box-decoration-break */
    boxDecoration?: 'slice' | 'clone';

    /** @see https://tailwindcss.com/docs/box-sizing */
    box?: 'border' | 'content';

    /** @see https://tailwindcss.com/docs/display */
    display?:
        | 'block'
        | 'inline-block'
        | 'inline'
        | 'flex'
        | 'inline-flex'
        | 'grid'
        | 'inline-grid'
        | 'contents'
        | 'table'
        | 'inline-table'
        | 'table-caption'
        | 'table-cell'
        | 'table-column'
        | 'table-column-group'
        | 'table-footer-group'
        | 'table-header-group'
        | 'table-row-group'
        | 'table-row'
        | 'flow-root'
        | 'list-item'
        | 'none';

    /**
     * Flex shorthand (flex-grow/shrink/basis). `flex: 1` → flex-1,
     * `flex: 'auto'` → flex-auto. This is NOT the removed `display: flex` sugar —
     * for display use `display: 'flex'`.
     * @see https://tailwindcss.com/docs/flex
     */
    flex?: 'auto' | 'initial' | 'none' | number | (string & {});
    /** Boolean sugar for sr-only */
    srOnly?: boolean;
    /** Boolean sugar for not-sr-only */
    notSrOnly?: boolean;
    /** Boolean sugar for container */
    container?: boolean;
    /** Boolean sugar for prose */
    prose?: boolean;
    /** Boolean sugar for prose-invert (requires @tailwindcss/typography plugin) */
    proseInvert?: boolean;

    /** @see https://tailwindcss.com/docs/float */
    float?: 'right' | 'left' | 'start' | 'end' | 'none';

    /** @see https://tailwindcss.com/docs/clear */
    clear?: 'left' | 'right' | 'both' | 'none' | 'start' | 'end';

    /** @see https://tailwindcss.com/docs/isolation */
    isolation?: 'isolate' | 'auto';

    /** @see https://tailwindcss.com/docs/object-fit */
    objectFit?: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down';

    /** @see https://tailwindcss.com/docs/object-position */
    objectPos?:
        | 'bottom'
        | 'center'
        | 'left'
        | 'left-bottom'
        | 'left-top'
        | 'right'
        | 'right-bottom'
        | 'right-top'
        | 'top'
        | (string & {});

    /** @see https://tailwindcss.com/docs/overflow */
    overflow?: 'auto' | 'hidden' | 'clip' | 'visible' | 'scroll';
    overflowX?: 'auto' | 'hidden' | 'clip' | 'visible' | 'scroll';
    overflowY?: 'auto' | 'hidden' | 'clip' | 'visible' | 'scroll';

    /** @see https://tailwindcss.com/docs/overscroll-behavior */
    overscroll?: 'auto' | 'contain' | 'none';
    overscrollX?: 'auto' | 'contain' | 'none';
    overscrollY?: 'auto' | 'contain' | 'none';

    /** @see https://tailwindcss.com/docs/position */
    position?: 'static' | 'fixed' | 'absolute' | 'relative' | 'sticky';

    /** @see https://tailwindcss.com/docs/top-right-bottom-left */
    inset?: SpacingValue;
    insetX?: SpacingValue;
    insetY?: SpacingValue;
    top?: NegativeSpacingValue;
    right?: NegativeSpacingValue;
    bottom?: NegativeSpacingValue;
    left?: NegativeSpacingValue;
    start?: SpacingValue;
    end?: SpacingValue;
    /** inset-inline-start (camelCase alias for start, emits inset-s-*) */
    insetS?: SpacingValue;
    /** inset-inline-end (camelCase alias for end, emits inset-e-*) */
    insetE?: SpacingValue;
    /** inset-block-start */
    insetBs?: SpacingValue;
    /** inset-block-end */
    insetBe?: SpacingValue;

    /** @see https://tailwindcss.com/docs/visibility */
    visibility?: 'visible' | 'hidden' | 'collapse';

    /** @see https://tailwindcss.com/docs/z-index */
    z?: 'auto' | 0 | 10 | 20 | 30 | 40 | 50 | number | (string & {});
}

// ============================================================================
// Flexbox & Grid Properties
// ============================================================================

/**
 *
 */
export interface FlexboxGridProps {
    /** @see https://tailwindcss.com/docs/flex-basis */
    basis?: SpacingScale | 'px' | 'auto' | 'full' | FractionValue | ContainerSize | (string & {});

    /** @see https://tailwindcss.com/docs/flex-direction */
    flexDir?: 'row' | 'row-reverse' | 'col' | 'col-reverse';

    /** @see https://tailwindcss.com/docs/flex-wrap */
    flexWrap?: 'wrap' | 'nowrap' | 'wrap-reverse';

    /** @see https://tailwindcss.com/docs/flex-grow */
    grow?: boolean | 0 | number | (string & {});

    /** @see https://tailwindcss.com/docs/flex-shrink */
    shrink?: boolean | 0 | number | (string & {});

    /** @see https://tailwindcss.com/docs/order */
    order?:
        | 'first'
        | 'last'
        | 'none'
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/grid-template-columns */
    gridCols?:
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 'none'
        | 'subgrid'
        | (string & {});

    /** @see https://tailwindcss.com/docs/grid-template-rows */
    gridRows?:
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 'none'
        | 'subgrid'
        | (string & {});

    /** @see https://tailwindcss.com/docs/grid-column */
    col?: 'auto' | number | (string & {});
    colSpan?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 'full' | number | (string & {});
    colStart?:
        | 'auto'
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 13
        | number
        | (string & {});
    colEnd?:
        | 'auto'
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 13
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/grid-row */
    row?: 'auto' | number | (string & {});
    rowSpan?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 'full' | number | (string & {});
    rowStart?:
        | 'auto'
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 13
        | number
        | (string & {});
    rowEnd?:
        | 'auto'
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 11
        | 12
        | 13
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/grid-auto-flow */
    gridFlow?: 'row' | 'col' | 'dense' | 'row-dense' | 'col-dense';

    /** @see https://tailwindcss.com/docs/grid-auto-columns */
    autoCols?: 'auto' | 'min' | 'max' | 'fr' | (string & {});

    /** @see https://tailwindcss.com/docs/grid-auto-rows */
    autoRows?: 'auto' | 'min' | 'max' | 'fr' | (string & {});

    /** @see https://tailwindcss.com/docs/gap */
    gap?: SpacingValue;
    gapX?: SpacingValue;
    gapY?: SpacingValue;

    /** @see https://tailwindcss.com/docs/justify-content */
    justify?:
        | 'normal'
        | 'start'
        | 'end'
        | 'center'
        | 'between'
        | 'around'
        | 'evenly'
        | 'stretch'
        | 'baseline'
        | 'safe-center'
        | 'safe-end';

    /** @see https://tailwindcss.com/docs/justify-items */
    justifyItems?: 'start' | 'end' | 'center' | 'stretch' | 'normal' | 'safe-center' | 'safe-end';

    /** @see https://tailwindcss.com/docs/justify-self */
    justifySelf?: 'auto' | 'start' | 'end' | 'center' | 'stretch' | 'safe-center' | 'safe-end';

    /** @see https://tailwindcss.com/docs/align-content */
    alignContent?:
        | 'normal'
        | 'start'
        | 'end'
        | 'center'
        | 'between'
        | 'around'
        | 'evenly'
        | 'baseline'
        | 'stretch';

    /** @see https://tailwindcss.com/docs/align-items */
    items?:
        | 'start'
        | 'end'
        | 'center'
        | 'baseline'
        | 'stretch'
        | 'safe-center'
        | 'safe-end'
        | (string & {});

    /** @see https://tailwindcss.com/docs/align-self */
    self?:
        | 'auto'
        | 'start'
        | 'end'
        | 'center'
        | 'stretch'
        | 'baseline'
        | 'safe-center'
        | 'safe-end'
        | (string & {});

    /** @see https://tailwindcss.com/docs/place-content */
    placeContent?:
        | 'center'
        | 'start'
        | 'end'
        | 'between'
        | 'around'
        | 'evenly'
        | 'baseline'
        | 'stretch'
        | 'safe-center'
        | 'safe-end';

    /** @see https://tailwindcss.com/docs/place-items */
    placeItems?: 'start' | 'end' | 'center' | 'baseline' | 'stretch' | 'safe-center' | 'safe-end';

    /** @see https://tailwindcss.com/docs/place-self */
    placeSelf?: 'auto' | 'start' | 'end' | 'center' | 'stretch' | 'safe-center' | 'safe-end';
}

// ============================================================================
// Spacing Properties
// ============================================================================

/**
 *
 */
export interface SpacingProps {
    /** Padding - all sides */
    p?: SpacingValue;
    /** Padding - X axis (left/right) */
    px?: SpacingValue;
    /** Padding - Y axis (top/bottom) */
    py?: SpacingValue;
    /** Padding - top */
    pt?: SpacingValue;
    /** Padding - right */
    pr?: SpacingValue;
    /** Padding - bottom */
    pb?: SpacingValue;
    /** Padding - left */
    pl?: SpacingValue;
    /** Padding - inline start (logical) */
    ps?: SpacingValue;
    /** Padding - inline end (logical) */
    pe?: SpacingValue;
    /** Padding - block-start (logical) */
    pbs?: SpacingValue;
    /** Padding - block-end (logical) */
    pbe?: SpacingValue;

    /** Margin - all sides */
    m?: NegativeSpacingValue;
    /** Margin - X axis (left/right) */
    mx?: NegativeSpacingValue;
    /** Margin - Y axis (top/bottom) */
    my?: NegativeSpacingValue;
    /** Margin - top */
    mt?: NegativeSpacingValue;
    /** Margin - right */
    mr?: NegativeSpacingValue;
    /** Margin - bottom */
    mb?: NegativeSpacingValue;
    /** Margin - left */
    ml?: NegativeSpacingValue;
    /** Margin - inline start (logical) */
    ms?: NegativeSpacingValue;
    /** Margin - inline end (logical) */
    me?: NegativeSpacingValue;
    /** Margin - block-start (logical) */
    mbs?: NegativeSpacingValue;
    /** Margin - block-end (logical) */
    mbe?: NegativeSpacingValue;

    /** Space between child elements - X axis */
    spaceX?: NegativeSpacingValue;
    /** Space between child elements - Y axis */
    spaceY?: NegativeSpacingValue;
    /** Reverse space-x direction */
    spaceXReverse?: boolean;
    /** Reverse space-y direction */
    spaceYReverse?: boolean;
}

// ============================================================================
// Sizing Properties
// ============================================================================

/**
 *
 */
export interface SizingProps {
    /** @see https://tailwindcss.com/docs/width */
    w?:
        | SpacingScale
        | 'px'
        | 'auto'
        | 'full'
        | 'screen'
        | 'svw'
        | 'lvw'
        | 'dvw'
        | 'min'
        | 'max'
        | 'fit'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/min-width */
    minW?: SpacingScale | 'px' | 'full' | 'min' | 'max' | 'fit' | FractionValue | (string & {});

    /** @see https://tailwindcss.com/docs/max-width */
    maxW?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'none'
        | 'prose'
        | 'min'
        | 'max'
        | 'fit'
        | ContainerSize
        | 'screen-sm'
        | 'screen-md'
        | 'screen-lg'
        | 'screen-xl'
        | 'screen-2xl'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/height */
    h?:
        | SpacingScale
        | 'px'
        | 'auto'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/min-height */
    minH?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | (string & {});

    /** @see https://tailwindcss.com/docs/max-height */
    maxH?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | (string & {});

    /** @see https://tailwindcss.com/docs/size */
    size?: SpacingScale | 'px' | 'auto' | 'full' | 'min' | 'max' | 'fit' | (string & {});

    /** @see https://tailwindcss.com/docs/block-size — block-size (logical height) */
    blockSize?:
        | SpacingScale
        | 'px'
        | 'auto'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/min-block-size */
    minBlockSize?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | (string & {});

    /** @see https://tailwindcss.com/docs/max-block-size */
    maxBlockSize?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'screen'
        | 'svh'
        | 'lvh'
        | 'dvh'
        | 'min'
        | 'max'
        | 'fit'
        | (string & {});

    /** @see https://tailwindcss.com/docs/inline-size — inline-size (logical width) */
    inlineSize?:
        | SpacingScale
        | 'px'
        | 'auto'
        | 'full'
        | 'screen'
        | 'svw'
        | 'lvw'
        | 'dvw'
        | 'min'
        | 'max'
        | 'fit'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/min-inline-size */
    minInlineSize?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'min'
        | 'max'
        | 'fit'
        | FractionValue
        | (string & {});

    /** @see https://tailwindcss.com/docs/max-inline-size */
    maxInlineSize?:
        | SpacingScale
        | 'px'
        | 'full'
        | 'none'
        | 'prose'
        | 'min'
        | 'max'
        | 'fit'
        | ContainerSize
        | FractionValue
        | (string & {});
}

// ============================================================================
// Typography Properties
// ============================================================================

/**
 *
 */
export interface TypographyProps {
    /** @see https://tailwindcss.com/docs/font-size — use `color` for text color, `textAlign` for alignment */
    text?:
        | 'xs'
        | 'sm'
        | 'base'
        | 'lg'
        | 'xl'
        | '2xl'
        | '3xl'
        | '4xl'
        | '5xl'
        | '6xl'
        | '7xl'
        | '8xl'
        | '9xl'
        | (string & {});

    /**
     * Font smoothing. `'grayscale'` → antialiased, `'subpixel'` → subpixel-antialiased.
     * The values name the rendering technique. (Distinct from the `grayscale` filter.)
     * @see https://tailwindcss.com/docs/font-smoothing
     */
    fontSmoothing?: 'grayscale' | 'subpixel';

    /**
     * Font style. `'italic'` → italic, `'normal'` → not-italic. Tailwind models
     * only these two; for oblique use `css: { fontStyle: 'oblique 10deg' }`.
     * @see https://tailwindcss.com/docs/font-style
     */
    fontStyle?: 'italic' | 'normal';

    /** @see https://tailwindcss.com/docs/font-weight */
    weight?:
        | 'thin'
        | 'extralight'
        | 'light'
        | 'normal'
        | 'medium'
        | 'semibold'
        | 'bold'
        | 'extrabold'
        | 'black'
        | 100
        | 200
        | 300
        | 400
        | 500
        | 600
        | 700
        | 800
        | 900
        | (string & {});
    /** Explicit font-family key. Use `font` for the short form */
    fontFamily?: 'sans' | 'serif' | 'mono' | CT_Fonts | (string & {});

    /** @see https://tailwindcss.com/docs/font-stretch */
    fontStretch?:
        | 'ultra-condensed'
        | 'extra-condensed'
        | 'condensed'
        | 'semi-condensed'
        | 'normal'
        | 'semi-expanded'
        | 'expanded'
        | 'extra-expanded'
        | 'ultra-expanded'
        | (string & {});

    /** @see https://tailwindcss.com/docs/font-variant-numeric */
    ordinal?: boolean;
    slashedZero?: boolean;
    liningNums?: boolean;
    oldstyleNums?: boolean;
    proportionalNums?: boolean;
    tabularNums?: boolean;
    diagonalFractions?: boolean;
    stackedFractions?: boolean;

    /** @see https://tailwindcss.com/docs/letter-spacing */
    tracking?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | 'widest' | (string & {});

    /** @see https://tailwindcss.com/docs/line-clamp */
    lineClamp?: 1 | 2 | 3 | 4 | 5 | 6 | 'none' | number | (string & {});

    /** @see https://tailwindcss.com/docs/line-height */
    leading?:
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
        | 10
        | 'none'
        | 'tight'
        | 'snug'
        | 'normal'
        | 'relaxed'
        | 'loose'
        | (string & {});

    /** @see https://tailwindcss.com/docs/list-style-image */
    listImg?: 'none' | (string & {});

    /** @see https://tailwindcss.com/docs/list-style-position */
    listPos?: 'inside' | 'outside';

    /** @see https://tailwindcss.com/docs/list-style-type */
    list?: 'none' | 'disc' | 'decimal' | (string & {});

    /** @see https://tailwindcss.com/docs/text-align */
    textAlign?: 'left' | 'center' | 'right' | 'justify' | 'start' | 'end';

    /** @see https://tailwindcss.com/docs/text-color */
    color?: ColorPropValue;

    /**
     * Text decoration line. `'underline'`, `'overline'`, `'line-through'`,
     * `'none'` (→ no-underline). Decoration color/style/thickness are separate
     * keys (decorationColor/decorationStyle/decorationThickness).
     * @see https://tailwindcss.com/docs/text-decoration-line
     */
    decoration?: 'underline' | 'overline' | 'line-through' | 'none' | (string & {});

    /** @see https://tailwindcss.com/docs/text-decoration-color */
    decorationColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/text-decoration-style */
    decorationStyle?: 'solid' | 'double' | 'dotted' | 'dashed' | 'wavy';

    /** @see https://tailwindcss.com/docs/text-decoration-thickness */
    decorationThickness?: 'auto' | 'from-font' | 0 | 1 | 2 | 4 | 8 | (string & {});

    /** @see https://tailwindcss.com/docs/text-underline-offset */
    underlineOffset?: 'auto' | 0 | 1 | 2 | 4 | 8 | (string & {});

    /**
     * Text transform. `'uppercase'`, `'lowercase'`, `'capitalize'`,
     * `'none'` (→ normal-case).
     * @see https://tailwindcss.com/docs/text-transform
     */
    textTransform?: 'uppercase' | 'lowercase' | 'capitalize' | 'none';

    /** @see https://tailwindcss.com/docs/text-overflow */
    truncate?: boolean;
    textEllipsis?: boolean;
    textClip?: boolean;

    /** @see https://tailwindcss.com/docs/text-wrap */
    textWrap?: 'wrap' | 'nowrap' | 'balance' | 'pretty';

    /** @see https://tailwindcss.com/docs/overflow-wrap (v4.1+) */
    wrap?: 'normal' | 'break-word' | 'anywhere';

    /** @see https://tailwindcss.com/docs/text-indent */
    indent?: SpacingValue;

    /** @see https://tailwindcss.com/docs/vertical-align */
    align?:
        | 'baseline'
        | 'top'
        | 'middle'
        | 'bottom'
        | 'text-top'
        | 'text-bottom'
        | 'sub'
        | 'super'
        | (string & {});

    /** @see https://tailwindcss.com/docs/whitespace */
    whitespace?: 'normal' | 'nowrap' | 'pre' | 'pre-line' | 'pre-wrap' | 'break-spaces';

    /** @see https://tailwindcss.com/docs/word-break */
    break?: 'normal' | 'all' | 'keep';

    /** @see https://tailwindcss.com/docs/hyphens */
    hyphens?: 'none' | 'manual' | 'auto';

    /** @see https://tailwindcss.com/docs/content */
    content?: 'none' | (string & {});

    /** @see https://tailwindcss.com/docs/font-feature-settings */
    fontFeatures?: string & {};

    /** @see https://tailwindcss.com/docs/forced-color-adjust */
    forcedColorAdjust?: 'auto' | 'none';
}

// ============================================================================
// Background Properties
// ============================================================================

/**
 *
 */
export interface BgImgGradient {
    gradient: 'linear' | 'radial' | 'conic';
    dir?: string | number;
    in?: 'srgb' | 'hsl' | 'oklab' | 'oklch' | 'longer' | 'shorter' | 'increasing' | 'decreasing';
}

/** Background-related sz prop definitions. */
export interface BackgroundProps {
    /** @see https://tailwindcss.com/docs/background-attachment */
    bgAttach?: 'fixed' | 'local' | 'scroll';

    /** @see https://tailwindcss.com/docs/background-clip */
    bgClip?: 'border' | 'padding' | 'content' | 'text';

    /** @see https://tailwindcss.com/docs/background-color */
    bg?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/background-origin */
    bgOrigin?: 'border' | 'padding' | 'content';

    /** @see https://tailwindcss.com/docs/background-position */
    bgPos?:
        | 'top-left'
        | 'top'
        | 'top-right'
        | 'left'
        | 'center'
        | 'right'
        | 'bottom-left'
        | 'bottom'
        | 'bottom-right'
        | (string & {});

    /** @see https://tailwindcss.com/docs/background-repeat */
    bgRepeat?: 'repeat' | 'no-repeat' | 'repeat-x' | 'repeat-y' | 'round' | 'space';

    /** @see https://tailwindcss.com/docs/background-size */
    bgSize?: 'auto' | 'cover' | 'contain' | (string & {});

    /** @see https://tailwindcss.com/docs/background-image */
    bgImg?: 'none' | BgImgGradient | (string & {});

    /** @see https://tailwindcss.com/docs/gradient-color-stops */
    from?: ColorPropValue;
    via?: ColorPropValue;
    to?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/gradient-color-stops (position) */
    fromPos?: number | (string & {});
    viaPos?: number | (string & {});
    toPos?: number | (string & {});
}

// ============================================================================
// Border Properties
// ============================================================================

/**
 *
 */
export interface BorderProps {
    /** @see https://tailwindcss.com/docs/border-radius */
    rounded?: BorderRadiusValue;
    roundedT?: BorderRadiusValue;
    roundedR?: BorderRadiusValue;
    roundedB?: BorderRadiusValue;
    roundedL?: BorderRadiusValue;
    roundedTl?: BorderRadiusValue;
    roundedTr?: BorderRadiusValue;
    roundedBl?: BorderRadiusValue;
    roundedBr?: BorderRadiusValue;
    roundedS?: BorderRadiusValue;
    roundedE?: BorderRadiusValue;
    roundedSs?: BorderRadiusValue;
    roundedSe?: BorderRadiusValue;
    roundedEs?: BorderRadiusValue;
    roundedEe?: BorderRadiusValue;

    /** @see https://tailwindcss.com/docs/border-width — use `borderColor` for border color */
    border?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderX?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderY?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderT?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderR?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderB?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderL?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderS?: boolean | 0 | 2 | 4 | 8 | (string & {});
    borderE?: boolean | 0 | 2 | 4 | 8 | (string & {});
    /** border-block-start width */
    borderBs?: boolean | 0 | 2 | 4 | 8 | (string & {});
    /** border-block-end width */
    borderBe?: boolean | 0 | 2 | 4 | 8 | (string & {});

    /** @see https://tailwindcss.com/docs/border-color */
    borderColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/border-style */
    borderStyle?: 'solid' | 'dashed' | 'dotted' | 'double' | 'hidden' | 'none';

    /** @see https://tailwindcss.com/docs/divide-width */
    divideX?: boolean | 0 | 2 | 4 | 8 | 'reverse' | (string & {});
    divideY?: boolean | 0 | 2 | 4 | 8 | 'reverse' | (string & {});

    /** @see https://tailwindcss.com/docs/divide-color */
    divideColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/divide-style */
    divideStyle?: 'solid' | 'dashed' | 'dotted' | 'double' | 'none';
    /** Reverse divide-x direction */
    divideXReverse?: boolean;
    /** Reverse divide-y direction */
    divideYReverse?: boolean;

    /** @see https://tailwindcss.com/docs/outline-width */
    outline?: boolean | 'none' | 0 | 1 | 2 | 4 | 8 | (string & {});

    /** @see https://tailwindcss.com/docs/outline-color */
    outlineColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/outline-style */
    outlineStyle?: 'solid' | 'dashed' | 'dotted' | 'double' | 'none';

    /** @see https://tailwindcss.com/docs/outline-offset */
    outlineOffset?: 0 | 1 | 2 | 4 | 8 | (string & {});

    /** @see https://tailwindcss.com/docs/ring-width */
    ring?: boolean | 0 | 1 | 2 | 4 | 8 | 'inset' | (string & {});

    /** @see https://tailwindcss.com/docs/ring-color */
    ringColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/ring-offset-width */
    ringOffset?: 0 | 1 | 2 | 4 | 8 | (string & {});

    /** @see https://tailwindcss.com/docs/ring-offset-color */
    ringOffsetColor?: ColorPropValue;
}

// ============================================================================
// Effects Properties
// ============================================================================

/**
 *
 */
export interface EffectsProps {
    /** @see https://tailwindcss.com/docs/box-shadow */
    shadow?: ShadowValue;

    /** @see https://tailwindcss.com/docs/box-shadow-color */
    shadowColor?: ColorPropValue;

    /** Text shadow */
    textShadow?: ShadowValue;
    /** Text shadow color */
    textShadowColor?: ColorPropValue;

    /** Inset shadow */
    insetShadow?: ShadowValue;
    /** Inset shadow color */
    insetShadowColor?: ColorPropValue;

    /** Drop shadow color */
    dropShadowColor?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/opacity */
    opacity?:
        | 0
        | 5
        | 10
        | 15
        | 20
        | 25
        | 30
        | 35
        | 40
        | 45
        | 50
        | 55
        | 60
        | 65
        | 70
        | 75
        | 80
        | 85
        | 90
        | 95
        | 100
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/mix-blend-mode */
    mixBlend?:
        | 'normal'
        | 'multiply'
        | 'screen'
        | 'overlay'
        | 'darken'
        | 'lighten'
        | 'color-dodge'
        | 'color-burn'
        | 'hard-light'
        | 'soft-light'
        | 'difference'
        | 'exclusion'
        | 'hue'
        | 'saturation'
        | 'color'
        | 'luminosity'
        | 'plus-darker'
        | 'plus-lighter';

    /** @see https://tailwindcss.com/docs/background-blend-mode */
    bgBlend?:
        | 'normal'
        | 'multiply'
        | 'screen'
        | 'overlay'
        | 'darken'
        | 'lighten'
        | 'color-dodge'
        | 'color-burn'
        | 'hard-light'
        | 'soft-light'
        | 'difference'
        | 'exclusion'
        | 'hue'
        | 'saturation'
        | 'color'
        | 'luminosity';
}

// ============================================================================
// Filter Properties
// ============================================================================

/**
 *
 */
export interface FilterProps {
    /** @see https://tailwindcss.com/docs/blur */
    blur?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | true | (string & {});

    /** @see https://tailwindcss.com/docs/brightness */
    brightness?: 0 | 50 | 75 | 90 | 95 | 100 | 105 | 110 | 125 | 150 | 200 | number | (string & {});

    /** @see https://tailwindcss.com/docs/contrast */
    contrast?: 0 | 50 | 75 | 100 | 125 | 150 | 200 | number | (string & {});

    /** @see https://tailwindcss.com/docs/drop-shadow */
    dropShadow?: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'none' | true | (string & {});

    /** @see https://tailwindcss.com/docs/grayscale */
    grayscale?: boolean | 0 | (string & {});

    /** @see https://tailwindcss.com/docs/hue-rotate */
    hueRotate?: 0 | 15 | 30 | 60 | 90 | 180 | number | (string & {});

    /** @see https://tailwindcss.com/docs/invert */
    invert?: boolean | 0 | (string & {});

    /** @see https://tailwindcss.com/docs/saturate */
    saturate?: 0 | 50 | 100 | 150 | 200 | number | (string & {});

    /** @see https://tailwindcss.com/docs/sepia */
    sepia?: boolean | 0 | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-blur */
    backdropBlur?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | true | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-brightness */
    backdropBrightness?:
        | 0
        | 50
        | 75
        | 90
        | 95
        | 100
        | 105
        | 110
        | 125
        | 150
        | 200
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-contrast */
    backdropContrast?: 0 | 50 | 75 | 100 | 125 | 150 | 200 | number | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-grayscale */
    backdropGrayscale?: boolean | 0 | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-hue-rotate */
    backdropHueRotate?: 0 | 15 | 30 | 60 | 90 | 180 | number | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-invert */
    backdropInvert?: boolean | 0 | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-opacity */
    backdropOpacity?:
        | 0
        | 5
        | 10
        | 15
        | 20
        | 25
        | 30
        | 35
        | 40
        | 45
        | 50
        | 55
        | 60
        | 65
        | 70
        | 75
        | 80
        | 85
        | 90
        | 95
        | 100
        | number
        | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-saturate */
    backdropSaturate?: 0 | 50 | 100 | 150 | 200 | number | (string & {});

    /** @see https://tailwindcss.com/docs/backdrop-sepia */
    backdropSepia?: boolean | 0 | (string & {});
}

// ============================================================================
// Transform Properties
// ============================================================================

/**
 *
 */
export interface TransformProps {
    /** @see https://tailwindcss.com/docs/scale */
    scale?:
        | 0
        | 50
        | 75
        | 90
        | 95
        | 100
        | 105
        | 110
        | 125
        | 150
        | 200
        | '3d'
        | number
        | (string & {});
    scaleX?: TransformProps['scale'];
    scaleY?: TransformProps['scale'];
    /** @see https://tailwindcss.com/docs/scale (Z-axis, 3D) */
    scaleZ?: TransformProps['scale'];

    /** @see https://tailwindcss.com/docs/rotate */
    rotate?: 0 | 1 | 2 | 3 | 6 | 12 | 45 | 90 | 180 | number | (string & {});
    /** @see https://tailwindcss.com/docs/rotate (X-axis, 3D) */
    rotateX?: TransformProps['rotate'];
    /** @see https://tailwindcss.com/docs/rotate (Y-axis, 3D) */
    rotateY?: TransformProps['rotate'];
    /** @see https://tailwindcss.com/docs/rotate (Z-axis, 3D) */
    rotateZ?: TransformProps['rotate'];

    /** @see https://tailwindcss.com/docs/translate — shorthand sets both axes */
    translate?: SpacingValue | FractionValue;
    /** @see https://tailwindcss.com/docs/translate */
    translateX?: SpacingValue | FractionValue;
    translateY?: SpacingValue | FractionValue;
    /** @see https://tailwindcss.com/docs/translate (Z-axis, 3D) */
    translateZ?: SpacingValue;

    /** @see https://tailwindcss.com/docs/skew */
    skewX?: 0 | 1 | 2 | 3 | 6 | 12 | number | (string & {});
    skewY?: 0 | 1 | 2 | 3 | 6 | 12 | number | (string & {});

    /** @see https://tailwindcss.com/docs/transform-origin */
    origin?:
        | 'center'
        | 'top'
        | 'top-right'
        | 'right'
        | 'bottom-right'
        | 'bottom'
        | 'bottom-left'
        | 'left'
        | 'top-left'
        | (string & {});

    /** @see https://tailwindcss.com/docs/transform */
    transform?: 'none' | 'gpu' | 'cpu';

    /** @see https://tailwindcss.com/docs/perspective */
    perspective?: 'none' | (string & {});
    perspectiveOrigin?: string & {};

    /** @see https://tailwindcss.com/docs/backface-visibility */
    backface?: 'visible' | 'hidden';
}

// ============================================================================
// Transition & Animation Properties
// ============================================================================

/**
 *
 */
export interface TransitionAnimationProps {
    /** @see https://tailwindcss.com/docs/transition-property */
    transition?:
        | boolean
        | 'none'
        | 'all'
        | 'colors'
        | 'opacity'
        | 'shadow'
        | 'transform'
        | (string & {});

    /** @see https://tailwindcss.com/docs/transition-duration */
    duration?: 0 | 75 | 100 | 150 | 200 | 300 | 500 | 700 | 1000 | number | (string & {});

    /** @see https://tailwindcss.com/docs/transition-timing-function */
    ease?: 'linear' | 'in' | 'out' | 'in-out' | (string & {});

    /** @see https://tailwindcss.com/docs/transition-delay */
    delay?: 0 | 75 | 100 | 150 | 200 | 300 | 500 | 700 | 1000 | number | (string & {});

    /** @see https://tailwindcss.com/docs/animation */
    animate?: 'none' | 'spin' | 'ping' | 'pulse' | 'bounce' | (string & {});

    /**
     * Animation delay — sets `animation-delay` (distinct from `delay` which sets `transition-delay`).
     * Number values are treated as milliseconds: `150` → `[animation-delay:150ms]`.
     */
    animationDelay?: 0 | 75 | 100 | 150 | 200 | 300 | 500 | 700 | 1000 | number | (string & {});
}

// ============================================================================
// Interactivity Properties
// ============================================================================

/**
 *
 */
export interface InteractivityProps {
    /** @see https://tailwindcss.com/docs/accent-color */
    accent?: 'auto' | ColorPropValue;

    /** @see https://tailwindcss.com/docs/appearance */
    appearance?: 'none' | 'auto';

    /** @see https://tailwindcss.com/docs/cursor */
    cursor?:
        | 'auto'
        | 'default'
        | 'pointer'
        | 'wait'
        | 'text'
        | 'move'
        | 'help'
        | 'not-allowed'
        | 'none'
        | 'context-menu'
        | 'progress'
        | 'cell'
        | 'crosshair'
        | 'vertical-text'
        | 'alias'
        | 'copy'
        | 'no-drop'
        | 'grab'
        | 'grabbing'
        | 'all-scroll'
        | 'col-resize'
        | 'row-resize'
        | 'n-resize'
        | 's-resize'
        | 'e-resize'
        | 'w-resize'
        | 'ne-resize'
        | 'nw-resize'
        | 'se-resize'
        | 'sw-resize'
        | 'ew-resize'
        | 'ns-resize'
        | 'nesw-resize'
        | 'nwse-resize'
        | 'zoom-in'
        | 'zoom-out'
        | (string & {});

    /** @see https://tailwindcss.com/docs/caret-color */
    caret?: 'auto' | ColorPropValue;

    /** @see https://tailwindcss.com/docs/pointer-events */
    pointerEvents?: 'none' | 'auto';

    /** @see https://tailwindcss.com/docs/field-sizing */
    fieldSizing?: 'fixed' | 'content';

    /** @see https://tailwindcss.com/docs/color-scheme */
    scheme?: 'normal' | 'dark' | 'light' | 'light-dark' | 'only-dark' | 'only-light';

    /** @see https://tailwindcss.com/docs/resize */
    resize?: 'none' | 'y' | 'x' | boolean;

    /** @see https://tailwindcss.com/docs/scroll-behavior */
    scroll?: 'auto' | 'smooth';

    /** @see https://tailwindcss.com/docs/scroll-margin */
    scrollM?: SpacingValue;
    scrollMx?: SpacingValue;
    scrollMy?: SpacingValue;
    scrollMt?: SpacingValue;
    scrollMr?: SpacingValue;
    scrollMb?: SpacingValue;
    scrollMl?: SpacingValue;
    scrollMs?: SpacingValue;
    scrollMe?: SpacingValue;

    /** @see https://tailwindcss.com/docs/scroll-padding */
    scrollP?: SpacingValue;
    scrollPx?: SpacingValue;
    scrollPy?: SpacingValue;
    scrollPt?: SpacingValue;
    scrollPr?: SpacingValue;
    scrollPb?: SpacingValue;
    scrollPl?: SpacingValue;
    scrollPs?: SpacingValue;
    scrollPe?: SpacingValue;
    /** scroll-padding-block-start */
    scrollPbs?: SpacingValue;
    /** scroll-padding-block-end */
    scrollPbe?: SpacingValue;
    /** scroll-margin-block-start */
    scrollMbs?: SpacingValue;
    /** scroll-margin-block-end */
    scrollMbe?: SpacingValue;

    /** @see https://tailwindcss.com/docs/scroll-snap-align */
    snapAlign?: 'start' | 'end' | 'center' | 'align-none';

    /** @see https://tailwindcss.com/docs/scroll-snap-stop */
    snapStop?: 'normal' | 'always';

    /** @see https://tailwindcss.com/docs/scroll-snap-type */
    snapType?: 'none' | 'x' | 'y' | 'both' | 'mandatory' | 'proximity';

    /** @see https://tailwindcss.com/docs/touch-action */
    touch?:
        | 'auto'
        | 'none'
        | 'pan-x'
        | 'pan-left'
        | 'pan-right'
        | 'pan-y'
        | 'pan-up'
        | 'pan-down'
        | 'pinch-zoom'
        | 'manipulation';

    /** @see https://tailwindcss.com/docs/user-select */
    select?: 'none' | 'text' | 'all' | 'auto';

    /** @see https://tailwindcss.com/docs/will-change */
    willChange?: 'auto' | 'scroll' | 'contents' | 'transform' | (string & {});

    /** @see https://tailwindcss.com/docs/scrollbar-width */
    scrollbar?: 'auto' | 'thin' | 'none';

    /** @see https://tailwindcss.com/docs/scrollbar-color */
    scrollbarThumb?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/scrollbar-color */
    scrollbarTrack?: ColorPropValue;

    /** @see https://tailwindcss.com/docs/scrollbar-gutter */
    scrollbarGutter?: 'auto' | 'stable' | 'both';

    /** @see https://tailwindcss.com/docs/zoom */
    zoom?: number | (string & {});

    /** @see https://tailwindcss.com/docs/tab-size */
    tabSize?: number | (string & {});
}

// ============================================================================
// SVG Properties
// ============================================================================

/**
 *
 */
export interface SvgProps {
    /** @see https://tailwindcss.com/docs/fill */
    fill?: 'none' | 'current' | ColorPropValue;

    /** @see https://tailwindcss.com/docs/stroke */
    stroke?: 'none' | 'current' | ColorPropValue;

    /** @see https://tailwindcss.com/docs/stroke-width */
    strokeWidth?: 0 | 1 | 2 | number | (string & {});
}

// ============================================================================
// Table Properties
// ============================================================================

/**
 *
 */
export interface TableProps {
    /** @see https://tailwindcss.com/docs/border-collapse */
    borderCollapse?: 'collapse' | 'separate';

    /** @see https://tailwindcss.com/docs/border-spacing */
    borderSpacing?: SpacingValue;
    borderSpacingX?: SpacingValue;
    borderSpacingY?: SpacingValue;

    /** @see https://tailwindcss.com/docs/table-layout */
    tableLayout?: 'auto' | 'fixed';

    /** @see https://tailwindcss.com/docs/caption-side */
    caption?: 'top' | 'bottom';
}

// ============================================================================
// Mask Properties
// ============================================================================

/**
 *
 */
export interface MaskProps {
    /** CSS mask shorthand */
    mask?: 'none' | (string & {});
    /** CSS mask-size */
    maskSize?: 'auto' | 'cover' | 'contain' | (string & {});
    /** CSS mask-position */
    maskPos?: string & {};
    /** CSS mask-repeat */
    maskRepeat?: 'repeat' | 'no-repeat' | 'repeat-x' | 'repeat-y' | 'round' | 'space';
    /** CSS mask-type (shape-rendering) */
    maskShape?: 'alpha' | 'luminance';
    /** CSS mask-clip */
    maskClip?: 'border' | 'content' | 'fill' | 'padding' | 'stroke' | 'view' | (string & {});
    /** CSS mask-origin */
    maskOrigin?: 'border' | 'content' | 'fill' | 'padding' | 'stroke' | 'view' | (string & {});

    /** Mask gradient from color stop (v4.1) */
    maskFrom?: ColorPropValue;
    /** Mask gradient via color stop (v4.1) */
    maskVia?: ColorPropValue;
    /** Mask gradient to color stop (v4.1) */
    maskTo?: ColorPropValue;
}

// ============================================================================
// Variant Modifiers (Recursive)
// ============================================================================

/**
 * Variant modifiers for pseudo-classes, breakpoints, and states.
 * These allow nesting SzProps for conditional styling.
 */
export interface VariantModifiers {
    // Pseudo-classes
    hover?: SzProps;
    focus?: SzProps;
    active?: SzProps;
    visited?: SzProps;
    target?: SzProps;
    first?: SzProps;
    last?: SzProps;
    only?: SzProps;
    odd?: SzProps;
    even?: SzProps;
    firstOfType?: SzProps;
    lastOfType?: SzProps;
    onlyOfType?: SzProps;
    empty?: SzProps;
    disabled?: SzProps;
    enabled?: SzProps;
    checked?: SzProps;
    indeterminate?: SzProps;
    default?: SzProps;
    required?: SzProps;
    valid?: SzProps;
    invalid?: SzProps;
    inRange?: SzProps;
    outOfRange?: SzProps;
    placeholderShown?: SzProps;
    autofill?: SzProps;
    readOnly?: SzProps;
    focusWithin?: SzProps;
    focusVisible?: SzProps;

    // Pseudo-elements
    before?: SzProps;
    after?: SzProps;
    placeholder?: SzProps;
    file?: SzProps;
    marker?: SzProps;
    selection?: SzProps;
    firstLine?: SzProps;
    firstLetter?: SzProps;
    backdrop?: SzProps;

    // Responsive breakpoints
    sm?: SzProps;
    md?: SzProps;
    lg?: SzProps;
    xl?: SzProps;
    '2xl'?: SzProps;

    // Container queries
    '@sm'?: SzProps;
    '@md'?: SzProps;
    '@lg'?: SzProps;
    '@xl'?: SzProps;
    '@2xl'?: SzProps;

    // Dark mode
    dark?: SzProps;
    light?: SzProps;

    // Motion preferences
    motionReduce?: SzProps;
    motionSafe?: SzProps;

    // Contrast preferences
    contrastMore?: SzProps;
    contrastLess?: SzProps;

    // Pointer preferences
    pointerFine?: SzProps;
    pointerCoarse?: SzProps;
    pointerNone?: SzProps;

    // Any-pointer preferences (v4.1)
    anyPointerFine?: SzProps;
    anyPointerCoarse?: SzProps;
    anyPointerNone?: SzProps;

    // Form validation (v4.1)
    userValid?: SzProps;
    userInvalid?: SzProps;

    // Details / inverted-colors / noscript (v4.1)
    detailsContent?: SzProps;
    invertedColors?: SzProps;
    noscript?: SzProps;

    // Forced-colors media variant
    forcedColors?: SzProps;

    // Print
    print?: SzProps;

    // Starting-style + inert state variants
    starting?: SzProps;
    inert?: SzProps;

    // Orientation
    portrait?: SzProps;
    landscape?: SzProps;

    // RTL/LTR
    rtl?: SzProps;
    ltr?: SzProps;

    // Group/Peer modifiers (true = class, string = named, object = nested variants)
    group?: boolean | string | SzProps;
    peer?: boolean | string | SzProps;

    // Not modifier
    not?: SzProps;

    // Has modifier
    has?: Record<string, SzProps>;

    // Aria states
    aria?: Record<string, SzProps>;

    // Data attributes
    data?: Record<string, SzProps>;

    // Supports queries
    supports?: Record<string, SzProps>;

    // Arbitrary variants (object-valued): container queries (`@container`,
    // `@container/sidebar`), arbitrary breakpoints (`min-[320px]`/`max-[600px]`),
    // and arbitrary selectors (`[&>span]`). A scalar typo key like `bgColor`
    // matches no pattern and is not a known prop → rejected by tsc. Force a
    // genuinely-new Tailwind utility csszyx has no key for yet with `@ts-expect-error`.
    // `@md`/`@lg`/`@max-[600px]` are container-query variants (object body);
    // `@container` / `@container/sidebar` are container-declaration markers
    // (boolean), so this `@`-sig accepts both.
    [variant: `@${string}`]: SzProps | boolean | undefined;
    [variant: `min-[${string}`]: SzProps | undefined;
    [variant: `max-[${string}`]: SzProps | undefined;
    [variant: `[${string}`]: SzProps | undefined;

    // Functional variants written as a flat string key (the compiler supports
    // each of these). Covers the bare-state form (`group-hover`, `aria-checked`),
    // the named form (`group-hover/sidebar`, `peer-focus/search`), and the
    // arbitrary-param form (`group-data-[active]`, `aria-[sort=asc]`,
    // `data-[state=open]`, `has-[:checked]`, `supports-[display:grid]`). The
    // nested object forms (`group: { hover: {} }`, `aria: { checked: {} }`)
    // remain available via the named props above; these cover the flat spelling.
    [variant: `group-${string}`]: SzProps | undefined;
    [variant: `peer-${string}`]: SzProps | undefined;
    [variant: `has-${string}`]: SzProps | undefined;
    [variant: `aria-${string}`]: SzProps | undefined;
    [variant: `data-${string}`]: SzProps | undefined;
    [variant: `not-${string}`]: SzProps | undefined;
    [variant: `in-${string}`]: SzProps | undefined;
    [variant: `nth-${string}`]: SzProps | undefined;
    [variant: `supports-${string}`]: SzProps | undefined;
}

// ============================================================================
// Combined SzProps Type
// ============================================================================

/**
 * Base sz props without variant modifiers (to prevent infinite recursion).
 */
export type SzPropsBase = LayoutProps &
    FlexboxGridProps &
    SpacingProps &
    SizingProps &
    TypographyProps &
    BackgroundProps &
    BorderProps &
    EffectsProps &
    FilterProps &
    TransformProps &
    TransitionAnimationProps &
    InteractivityProps &
    SvgProps &
    TableProps &
    MaskProps & {
        /**
         * Arbitrary CSS escape hatch — for CSS properties with no sz/Tailwind equivalent.
         * Keys are camelCase CSS properties (or `--custom-property` for CSS vars).
         * Each entry generates a Tailwind arbitrary-property class: `[prop:value]`.
         *
         * @example
         * { css: { writingMode: 'vertical-lr', touchAction: 'none' } }
         * // → [writing-mode:vertical-lr] [touch-action:none]
         *
         * { css: { '--my-color': 'red' } }
         * // → [--my-color:red]
         */
        css?: CSS.Properties & { [cssVar: `--${string}`]: string | number };
    };

/**
 * Complete sz prop type with all properties and variant modifiers.
 *
 * @example
 * ```tsx
 * <div sz={{ p: 4, bg: 'blue-500', hover: { bg: 'blue-700' } }} />
 * ```
 */
export type SzProps = SzPropsBase & VariantModifiers;

/**
 * Array element type for sz array composition — each element is a style object or a falsy
 * conditional guard (`false | null | undefined` are skipped at runtime by `_szMerge`).
 */
export type SzArrayElement = SzProps | false | null | undefined;

/**
 * All accepted forms of the `sz` prop:
 * - A plain Tailwind class string: `sz="p-4 bg-blue-500"`
 * - A style object: `sz={{ p: 4, bg: 'blue-500' }}`
 * - An array of style objects for composition: `sz={[layout, text, isActive && active]}`
 *
 * @example
 * ```tsx
 * <div sz="p-4 bg-blue-500 hover:bg-blue-700" />
 * <div sz={{ p: 4, bg: 'blue-500' }} />
 * <div sz={[base, isActive && activeStyle]} />
 * ```
 */
export type SzPropValue = string | SzProps | SzArrayElement[];
