import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';
import {
    BOOLEAN_SHORTHANDS,
    KNOWN_VARIANTS,
    PROPERTY_MAP,
    SUGGESTION_MAP,
} from '../../compiler/src/transform-core.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(here, '../src/tooling.generated.ts');
const check = process.argv.includes('--check');

/** Read the top-level VALUE_SUGGESTIONS keys without executing the module.
 * value-suggestions.ts sits in a commonjs package, so importing it from this
 * ESM script hits loader interop edge cases; parsing its AST is hermetic. */
const readValueSuggestionKeys = async () => {
    const source = await readFile(resolve(here, '../src/value-suggestions.ts'), 'utf8');
    const sourceFile = ts.createSourceFile('value-suggestions.ts', source, ts.ScriptTarget.Latest);
    const keys = [];
    for (const statement of sourceFile.statements) {
        if (!ts.isVariableStatement(statement)) continue;
        for (const declaration of statement.declarationList.declarations) {
            if (
                !ts.isIdentifier(declaration.name) ||
                declaration.name.text !== 'VALUE_SUGGESTIONS' ||
                !declaration.initializer ||
                !ts.isObjectLiteralExpression(declaration.initializer)
            )
                continue;
            for (const property of declaration.initializer.properties) {
                if (!ts.isPropertyAssignment(property)) continue;
                if (ts.isIdentifier(property.name) || ts.isStringLiteral(property.name))
                    keys.push(property.name.text);
            }
        }
    }
    return keys;
};

// Drift gate: every curated value key must be a real sz key, or its suggestions
// are dead (never surface at a value slot). Runs in both generate and --check.
const validKeys = new Set([...Object.keys(PROPERTY_MAP), ...BOOLEAN_SHORTHANDS]);
const orphanKeys = (await readValueSuggestionKeys()).filter(key => !validKeys.has(key));
if (orphanKeys.length > 0) {
    throw new Error(
        `value-suggestions.ts keys absent from PROPERTY_MAP ∪ BOOLEAN_SHORTHANDS (dead suggestions): ${orphanKeys.join(', ')}`,
    );
}

const serialize = value => JSON.stringify(value, null, 4);
const generated = `/** GENERATED by packages/tooling-metadata/scripts/generate.mjs. */
export const METADATA_SCHEMA_VERSION = 1 as const;
export const PROPERTY_MAP = ${serialize(PROPERTY_MAP)} as const;
export const BOOLEAN_SHORTHANDS = ${serialize([...BOOLEAN_SHORTHANDS].sort())} as const;
export const KNOWN_VARIANTS = ${serialize([...KNOWN_VARIANTS].sort())} as const;
export const SUGGESTION_MAP = ${serialize(SUGGESTION_MAP)} as const;
export { VALUE_SUGGESTIONS } from './value-suggestions';
`;

if (check) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== generated) {
        throw new Error('tooling metadata is stale; run pnpm --filter @csszyx/tooling-metadata generate');
    }
} else {
    await writeFile(outputPath, generated);
}
